/* 
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.DLP.Client;
using Cloudmersive.APIClient.NETCore.DLP.Model;

namespace Cloudmersive.APIClient.NETCore.DLP.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDetectApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Detect User Data in Document Image
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpDetectionResponse</returns>
        DlpDetectionResponse DetectDocument (DlpDocumentDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Document Image
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpDetectionResponse</returns>
        ApiResponse<DlpDetectionResponse> DetectDocumentWithHttpInfo (DlpDocumentDetectionRequest body = null);
        /// <summary>
        /// Detect User Data in Document Image (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpAdvancedDetectionResponse</returns>
        DlpAdvancedDetectionResponse DetectDocumentAdvanced (DlpAdvancedDocumentDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Document Image (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpAdvancedDetectionResponse</returns>
        ApiResponse<DlpAdvancedDetectionResponse> DetectDocumentAdvancedWithHttpInfo (DlpAdvancedDocumentDetectionRequest body = null);
        /// <summary>
        /// Detect User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpDetectionResponse</returns>
        DlpDetectionResponse DetectText (DlpDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpDetectionResponse</returns>
        ApiResponse<DlpDetectionResponse> DetectTextWithHttpInfo (DlpDetectionRequest body = null);
        /// <summary>
        /// Detect User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpAdvancedDetectionResponse</returns>
        DlpAdvancedDetectionResponse DetectTextAdvanced (DlpAdvancedDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpAdvancedDetectionResponse</returns>
        ApiResponse<DlpAdvancedDetectionResponse> DetectTextAdvancedWithHttpInfo (DlpAdvancedDetectionRequest body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Detect User Data in Document Image
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpDetectionResponse</returns>
        System.Threading.Tasks.Task<DlpDetectionResponse> DetectDocumentAsync (DlpDocumentDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Document Image
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpDetectionResponse>> DetectDocumentAsyncWithHttpInfo (DlpDocumentDetectionRequest body = null);
        /// <summary>
        /// Detect User Data in Document Image (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpAdvancedDetectionResponse</returns>
        System.Threading.Tasks.Task<DlpAdvancedDetectionResponse> DetectDocumentAdvancedAsync (DlpAdvancedDocumentDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Document Image (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpAdvancedDetectionResponse>> DetectDocumentAdvancedAsyncWithHttpInfo (DlpAdvancedDocumentDetectionRequest body = null);
        /// <summary>
        /// Detect User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpDetectionResponse</returns>
        System.Threading.Tasks.Task<DlpDetectionResponse> DetectTextAsync (DlpDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Input Text
        /// </summary>
        /// <remarks>
        /// Detects configurable types of user data in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpDetectionResponse>> DetectTextAsyncWithHttpInfo (DlpDetectionRequest body = null);
        /// <summary>
        /// Detect User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpAdvancedDetectionResponse</returns>
        System.Threading.Tasks.Task<DlpAdvancedDetectionResponse> DetectTextAdvancedAsync (DlpAdvancedDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Input Text (Advanced)
        /// </summary>
        /// <remarks>
        /// Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpAdvancedDetectionResponse>> DetectTextAdvancedAsyncWithHttpInfo (DlpAdvancedDetectionRequest body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DetectApi : IDetectApi
    {
        private Cloudmersive.APIClient.NETCore.DLP.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DetectApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DetectApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.DLP.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DetectApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DetectApi(Cloudmersive.APIClient.NETCore.DLP.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.DLP.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.DLP.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.DLP.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Detect User Data in Document Image Detects configurable types of user data in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpDetectionResponse</returns>
        public DlpDetectionResponse DetectDocument (DlpDocumentDetectionRequest body = null)
        {
             ApiResponse<DlpDetectionResponse> localVarResponse = DetectDocumentWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Document Image Detects configurable types of user data in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpDetectionResponse</returns>
        public ApiResponse< DlpDetectionResponse > DetectDocumentWithHttpInfo (DlpDocumentDetectionRequest body = null)
        {

            var localVarPath = "./dlp/detect/document";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectDocument", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpDetectionResponse)));
        }

        /// <summary>
        /// Detect User Data in Document Image Detects configurable types of user data in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpDetectionResponse</returns>
        public async System.Threading.Tasks.Task<DlpDetectionResponse> DetectDocumentAsync (DlpDocumentDetectionRequest body = null)
        {
             ApiResponse<DlpDetectionResponse> localVarResponse = await DetectDocumentAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Detect User Data in Document Image Detects configurable types of user data in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DlpDetectionResponse>> DetectDocumentAsyncWithHttpInfo (DlpDocumentDetectionRequest body = null)
        {

            var localVarPath = "./dlp/detect/document";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectDocument", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpDetectionResponse)));
        }

        /// <summary>
        /// Detect User Data in Document Image (Advanced) Detects 29 configurable types of user data including health-related PHI in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpAdvancedDetectionResponse</returns>
        public DlpAdvancedDetectionResponse DetectDocumentAdvanced (DlpAdvancedDocumentDetectionRequest body = null)
        {
             ApiResponse<DlpAdvancedDetectionResponse> localVarResponse = DetectDocumentAdvancedWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Document Image (Advanced) Detects 29 configurable types of user data including health-related PHI in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpAdvancedDetectionResponse</returns>
        public ApiResponse< DlpAdvancedDetectionResponse > DetectDocumentAdvancedWithHttpInfo (DlpAdvancedDocumentDetectionRequest body = null)
        {

            var localVarPath = "./dlp/detect/document/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectDocumentAdvanced", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpAdvancedDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpAdvancedDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpAdvancedDetectionResponse)));
        }

        /// <summary>
        /// Detect User Data in Document Image (Advanced) Detects 29 configurable types of user data including health-related PHI in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpAdvancedDetectionResponse</returns>
        public async System.Threading.Tasks.Task<DlpAdvancedDetectionResponse> DetectDocumentAdvancedAsync (DlpAdvancedDocumentDetectionRequest body = null)
        {
             ApiResponse<DlpAdvancedDetectionResponse> localVarResponse = await DetectDocumentAdvancedAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Detect User Data in Document Image (Advanced) Detects 29 configurable types of user data including health-related PHI in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DlpAdvancedDetectionResponse>> DetectDocumentAdvancedAsyncWithHttpInfo (DlpAdvancedDocumentDetectionRequest body = null)
        {

            var localVarPath = "./dlp/detect/document/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectDocumentAdvanced", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpAdvancedDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpAdvancedDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpAdvancedDetectionResponse)));
        }

        /// <summary>
        /// Detect User Data in Input Text Detects configurable types of user data in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpDetectionResponse</returns>
        public DlpDetectionResponse DetectText (DlpDetectionRequest body = null)
        {
             ApiResponse<DlpDetectionResponse> localVarResponse = DetectTextWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Input Text Detects configurable types of user data in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpDetectionResponse</returns>
        public ApiResponse< DlpDetectionResponse > DetectTextWithHttpInfo (DlpDetectionRequest body = null)
        {

            var localVarPath = "./dlp/detect/text";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectText", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpDetectionResponse)));
        }

        /// <summary>
        /// Detect User Data in Input Text Detects configurable types of user data in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpDetectionResponse</returns>
        public async System.Threading.Tasks.Task<DlpDetectionResponse> DetectTextAsync (DlpDetectionRequest body = null)
        {
             ApiResponse<DlpDetectionResponse> localVarResponse = await DetectTextAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Detect User Data in Input Text Detects configurable types of user data in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DlpDetectionResponse>> DetectTextAsyncWithHttpInfo (DlpDetectionRequest body = null)
        {

            var localVarPath = "./dlp/detect/text";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectText", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpDetectionResponse)));
        }

        /// <summary>
        /// Detect User Data in Input Text (Advanced) Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpAdvancedDetectionResponse</returns>
        public DlpAdvancedDetectionResponse DetectTextAdvanced (DlpAdvancedDetectionRequest body = null)
        {
             ApiResponse<DlpAdvancedDetectionResponse> localVarResponse = DetectTextAdvancedWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Input Text (Advanced) Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpAdvancedDetectionResponse</returns>
        public ApiResponse< DlpAdvancedDetectionResponse > DetectTextAdvancedWithHttpInfo (DlpAdvancedDetectionRequest body = null)
        {

            var localVarPath = "./dlp/detect/text/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectTextAdvanced", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpAdvancedDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpAdvancedDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpAdvancedDetectionResponse)));
        }

        /// <summary>
        /// Detect User Data in Input Text (Advanced) Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpAdvancedDetectionResponse</returns>
        public async System.Threading.Tasks.Task<DlpAdvancedDetectionResponse> DetectTextAdvancedAsync (DlpAdvancedDetectionRequest body = null)
        {
             ApiResponse<DlpAdvancedDetectionResponse> localVarResponse = await DetectTextAdvancedAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Detect User Data in Input Text (Advanced) Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpAdvancedDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DlpAdvancedDetectionResponse>> DetectTextAdvancedAsyncWithHttpInfo (DlpAdvancedDetectionRequest body = null)
        {

            var localVarPath = "./dlp/detect/text/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectTextAdvanced", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpAdvancedDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpAdvancedDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpAdvancedDetectionResponse)));
        }

    }
}
