/* 
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.DLP.Client;
using Cloudmersive.APIClient.NETCore.DLP.Model;

namespace Cloudmersive.APIClient.NETCore.DLP.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITasksBatchJobApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpBatchJobResult</returns>
        DlpBatchJobResult DetectAudioAdvancedBatchJob (DlpAdvancedAudioDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        ApiResponse<DlpBatchJobResult> DetectAudioAdvancedBatchJobWithHttpInfo (DlpAdvancedAudioDetectionRequest body = null);
        /// <summary>
        /// Detect User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpBatchJobResult</returns>
        DlpBatchJobResult DetectAudioBatchJob (DlpAudioDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        ApiResponse<DlpBatchJobResult> DetectAudioBatchJobWithHttpInfo (DlpAudioDetectionRequest body = null);
        /// <summary>
        /// Get the status and result of a DLP Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>DlpBatchJobStatusResult</returns>
        DlpBatchJobStatusResult GetAsyncJobStatus (string asyncJobID = null);

        /// <summary>
        /// Get the status and result of a DLP Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobStatusResult</returns>
        ApiResponse<DlpBatchJobStatusResult> GetAsyncJobStatusWithHttpInfo (string asyncJobID = null);
        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpBatchJobResult</returns>
        DlpBatchJobResult RedactAudioAdvancedBatchJob (DlpAdvancedAudioRedactionRequest body = null);

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        ApiResponse<DlpBatchJobResult> RedactAudioAdvancedBatchJobWithHttpInfo (DlpAdvancedAudioRedactionRequest body = null);
        /// <summary>
        /// Redact User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpBatchJobResult</returns>
        DlpBatchJobResult RedactAudioBatchJob (DlpAudioRedactionRequest body = null);

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        ApiResponse<DlpBatchJobResult> RedactAudioBatchJobWithHttpInfo (DlpAudioRedactionRequest body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobResult> DetectAudioAdvancedBatchJobAsync (DlpAdvancedAudioDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> DetectAudioAdvancedBatchJobAsyncWithHttpInfo (DlpAdvancedAudioDetectionRequest body = null);
        /// <summary>
        /// Detect User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobResult> DetectAudioBatchJobAsync (DlpAudioDetectionRequest body = null);

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> DetectAudioBatchJobAsyncWithHttpInfo (DlpAudioDetectionRequest body = null);
        /// <summary>
        /// Get the status and result of a DLP Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>Task of DlpBatchJobStatusResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobStatusResult> GetAsyncJobStatusAsync (string asyncJobID = null);

        /// <summary>
        /// Get the status and result of a DLP Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobStatusResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobStatusResult>> GetAsyncJobStatusAsyncWithHttpInfo (string asyncJobID = null);
        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobResult> RedactAudioAdvancedBatchJobAsync (DlpAdvancedAudioRedactionRequest body = null);

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> RedactAudioAdvancedBatchJobAsyncWithHttpInfo (DlpAdvancedAudioRedactionRequest body = null);
        /// <summary>
        /// Redact User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        System.Threading.Tasks.Task<DlpBatchJobResult> RedactAudioBatchJobAsync (DlpAudioRedactionRequest body = null);

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> RedactAudioBatchJobAsyncWithHttpInfo (DlpAudioRedactionRequest body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TasksBatchJobApi : ITasksBatchJobApi
    {
        private Cloudmersive.APIClient.NETCore.DLP.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TasksBatchJobApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TasksBatchJobApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.DLP.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TasksBatchJobApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TasksBatchJobApi(Cloudmersive.APIClient.NETCore.DLP.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.DLP.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.DLP.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.DLP.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpBatchJobResult</returns>
        public DlpBatchJobResult DetectAudioAdvancedBatchJob (DlpAdvancedAudioDetectionRequest body = null)
        {
             ApiResponse<DlpBatchJobResult> localVarResponse = DetectAudioAdvancedBatchJobWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        public ApiResponse< DlpBatchJobResult > DetectAudioAdvancedBatchJobWithHttpInfo (DlpAdvancedAudioDetectionRequest body = null)
        {

            var localVarPath = "./dlp/batch-job/detect/audio/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectAudioAdvancedBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobResult)));
        }

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobResult> DetectAudioAdvancedBatchJobAsync (DlpAdvancedAudioDetectionRequest body = null)
        {
             ApiResponse<DlpBatchJobResult> localVarResponse = await DetectAudioAdvancedBatchJobAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Detect User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> DetectAudioAdvancedBatchJobAsyncWithHttpInfo (DlpAdvancedAudioDetectionRequest body = null)
        {

            var localVarPath = "./dlp/batch-job/detect/audio/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectAudioAdvancedBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobResult)));
        }

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpBatchJobResult</returns>
        public DlpBatchJobResult DetectAudioBatchJob (DlpAudioDetectionRequest body = null)
        {
             ApiResponse<DlpBatchJobResult> localVarResponse = DetectAudioBatchJobWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        public ApiResponse< DlpBatchJobResult > DetectAudioBatchJobWithHttpInfo (DlpAudioDetectionRequest body = null)
        {

            var localVarPath = "./dlp/batch-job/detect/audio";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectAudioBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobResult)));
        }

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobResult> DetectAudioBatchJobAsync (DlpAudioDetectionRequest body = null)
        {
             ApiResponse<DlpBatchJobResult> localVarResponse = await DetectAudioBatchJobAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Detect User Data in Audio File as a Batch Job Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> DetectAudioBatchJobAsyncWithHttpInfo (DlpAudioDetectionRequest body = null)
        {

            var localVarPath = "./dlp/batch-job/detect/audio";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetectAudioBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobResult)));
        }

        /// <summary>
        /// Get the status and result of a DLP Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>DlpBatchJobStatusResult</returns>
        public DlpBatchJobStatusResult GetAsyncJobStatus (string asyncJobID = null)
        {
             ApiResponse<DlpBatchJobStatusResult> localVarResponse = GetAsyncJobStatusWithHttpInfo(asyncJobID);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the status and result of a DLP Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobStatusResult</returns>
        public ApiResponse< DlpBatchJobStatusResult > GetAsyncJobStatusWithHttpInfo (string asyncJobID = null)
        {

            var localVarPath = "./dlp/batch-job/status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (asyncJobID != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "AsyncJobID", asyncJobID)); // query parameter

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAsyncJobStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobStatusResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobStatusResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobStatusResult)));
        }

        /// <summary>
        /// Get the status and result of a DLP Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>Task of DlpBatchJobStatusResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobStatusResult> GetAsyncJobStatusAsync (string asyncJobID = null)
        {
             ApiResponse<DlpBatchJobStatusResult> localVarResponse = await GetAsyncJobStatusAsyncWithHttpInfo(asyncJobID);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the status and result of a DLP Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobStatusResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DlpBatchJobStatusResult>> GetAsyncJobStatusAsyncWithHttpInfo (string asyncJobID = null)
        {

            var localVarPath = "./dlp/batch-job/status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (asyncJobID != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "AsyncJobID", asyncJobID)); // query parameter

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAsyncJobStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobStatusResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobStatusResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobStatusResult)));
        }

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpBatchJobResult</returns>
        public DlpBatchJobResult RedactAudioAdvancedBatchJob (DlpAdvancedAudioRedactionRequest body = null)
        {
             ApiResponse<DlpBatchJobResult> localVarResponse = RedactAudioAdvancedBatchJobWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        public ApiResponse< DlpBatchJobResult > RedactAudioAdvancedBatchJobWithHttpInfo (DlpAdvancedAudioRedactionRequest body = null)
        {

            var localVarPath = "./dlp/batch-job/redact/audio/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RedactAudioAdvancedBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobResult)));
        }

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobResult> RedactAudioAdvancedBatchJobAsync (DlpAdvancedAudioRedactionRequest body = null)
        {
             ApiResponse<DlpBatchJobResult> localVarResponse = await RedactAudioAdvancedBatchJobAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Redact User Data in Audio File (Advanced) as a Batch Job Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> RedactAudioAdvancedBatchJobAsyncWithHttpInfo (DlpAdvancedAudioRedactionRequest body = null)
        {

            var localVarPath = "./dlp/batch-job/redact/audio/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RedactAudioAdvancedBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobResult)));
        }

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>DlpBatchJobResult</returns>
        public DlpBatchJobResult RedactAudioBatchJob (DlpAudioRedactionRequest body = null)
        {
             ApiResponse<DlpBatchJobResult> localVarResponse = RedactAudioBatchJobWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>ApiResponse of DlpBatchJobResult</returns>
        public ApiResponse< DlpBatchJobResult > RedactAudioBatchJobWithHttpInfo (DlpAudioRedactionRequest body = null)
        {

            var localVarPath = "./dlp/batch-job/redact/audio";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RedactAudioBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobResult)));
        }

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of DlpBatchJobResult</returns>
        public async System.Threading.Tasks.Task<DlpBatchJobResult> RedactAudioBatchJobAsync (DlpAudioRedactionRequest body = null)
        {
             ApiResponse<DlpBatchJobResult> localVarResponse = await RedactAudioBatchJobAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Redact User Data in Audio File as a Batch Job Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Input request (optional)</param>
        /// <returns>Task of ApiResponse (DlpBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DlpBatchJobResult>> RedactAudioBatchJobAsyncWithHttpInfo (DlpAudioRedactionRequest body = null)
        {

            var localVarPath = "./dlp/batch-job/redact/audio";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RedactAudioBatchJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DlpBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (DlpBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DlpBatchJobResult)));
        }

    }
}
