/* 
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DLP.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DLP.Model
{
    /// <summary>
    /// Caller-defined custom PII field. The redaction LLM will look for content matching  the description and redact it as a semantic tag derived from the title  (e.g. title \&quot;internal participant code\&quot; → tag [INTERNAL-PARTICIPANT-CODE]).
    /// </summary>
    [DataContract]
    public partial class CustomPiiField :  IEquatable<CustomPiiField>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomPiiField" /> class.
        /// </summary>
        /// <param name="title">Short title for the custom field, also used to derive the semantic tag (uppercased, spaces/underscores replaced with hyphens)..</param>
        /// <param name="description">Description of what this field looks like, used to instruct the redaction LLM. Be specific so the LLM can locate matches..</param>
        public CustomPiiField(string title = default(string), string description = default(string))
        {
            this.Title = title;
            this.Description = description;
        }
        
        /// <summary>
        /// Short title for the custom field, also used to derive the semantic tag (uppercased, spaces/underscores replaced with hyphens).
        /// </summary>
        /// <value>Short title for the custom field, also used to derive the semantic tag (uppercased, spaces/underscores replaced with hyphens).</value>
        [DataMember(Name="Title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Description of what this field looks like, used to instruct the redaction LLM. Be specific so the LLM can locate matches.
        /// </summary>
        /// <value>Description of what this field looks like, used to instruct the redaction LLM. Be specific so the LLM can locate matches.</value>
        [DataMember(Name="Description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CustomPiiField {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CustomPiiField);
        }

        /// <summary>
        /// Returns true if CustomPiiField instances are equal
        /// </summary>
        /// <param name="input">Instance of CustomPiiField to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomPiiField input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }
    }

}
