/* 
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DLP.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DLP.Model
{
    /// <summary>
    /// Request object for advanced DLP document detection with 29 PII detection types including health-related data.
    /// </summary>
    [DataContract]
    public partial class DlpAdvancedDocumentDetectionRequest :  IEquatable<DlpAdvancedDocumentDetectionRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpAdvancedDocumentDetectionRequest" /> class.
        /// </summary>
        /// <param name="inputFile">Document file bytes (PDF, DOCX, PNG, or JPG) to scan for PII and sensitive data..</param>
        /// <param name="fileName">Optional. Name of the input file including extension, used for format detection. If not provided, format is detected from file contents..</param>
        /// <param name="recognitionMode">Optional. Recognition mode for image processing. Options: null (default), \&quot;Fast\&quot;, \&quot;FastPlus\&quot;, \&quot;FastMini\&quot;..</param>
        /// <param name="allowEmailAddress">Set to true to allow email addresses in the document and not flag them as PII..</param>
        /// <param name="allowPhoneNumber">Set to true to allow phone numbers in the document and not flag them as PII..</param>
        /// <param name="allowStreetAddress">Set to true to allow street addresses in the document and not flag them as PII..</param>
        /// <param name="allowPersonName">Set to true to allow person names in the document and not flag them as PII..</param>
        /// <param name="allowBirthDate">Set to true to allow birth dates in the document and not flag them as PII..</param>
        /// <param name="allowPassportNumber">Set to true to allow passport numbers in the document and not flag them as PII..</param>
        /// <param name="allowDriversLicense">Set to true to allow drivers license numbers in the document and not flag them as PII..</param>
        /// <param name="allowSocialSecurityNumber">Set to true to allow social security numbers in the document and not flag them as PII..</param>
        /// <param name="allowTaxpayerID">Set to true to allow taxpayer IDs in the document and not flag them as PII..</param>
        /// <param name="allowCreditCardNumber">Set to true to allow credit card numbers in the document and not flag them as PII..</param>
        /// <param name="allowCreditCardExpirationDate">Set to true to allow credit card expiration dates in the document and not flag them as PII..</param>
        /// <param name="allowCreditCardVerificationCode">Set to true to allow credit card verification codes in the document and not flag them as PII..</param>
        /// <param name="allowBankAccountNumber">Set to true to allow bank account numbers in the document and not flag them as PII..</param>
        /// <param name="allowIBAN">Set to true to allow IBANs in the document and not flag them as PII..</param>
        /// <param name="allowHealthInsuranceNumber">Set to true to allow health insurance numbers in the document and not flag them as PII..</param>
        /// <param name="allowBearerToken">Set to true to allow bearer tokens in the document and not flag them as PII..</param>
        /// <param name="allowHttpCookie">Set to true to allow HTTP cookies in the document and not flag them as PII..</param>
        /// <param name="allowPrivateKeys">Set to true to allow private keys in the document and not flag them as PII..</param>
        /// <param name="allowCredentials">Set to true to allow credentials (usernames/passwords) in the document and not flag them as PII..</param>
        /// <param name="allowDeepWebUrls">Set to true to allow deep web URLs (.onion) in the document and not flag them as PII..</param>
        /// <param name="allowSourceCode">Set to true to allow source code in the document and not flag it as sensitive data..</param>
        /// <param name="allowIpAddress">Set to true to allow IP addresses in the document and not flag them as PII..</param>
        /// <param name="allowMacAddress">Set to true to allow MAC addresses in the document and not flag them as PII..</param>
        /// <param name="allowHealthInsuranceMemberID">Set to true to allow health insurance member IDs in the document and not flag them as PHI..</param>
        /// <param name="allowHealthInjuryOrDisease">Set to true to allow references to injuries or diseases in the document and not flag them as PHI..</param>
        /// <param name="allowHealthTypeOfTreatment">Set to true to allow references to types of medical treatment in the document and not flag them as PHI..</param>
        /// <param name="allowHealthDateAndTimeOfTreatment">Set to true to allow dates and times of medical treatment in the document and not flag them as PHI..</param>
        /// <param name="allowHealthPlanBeneficiaryNumber">Set to true to allow health plan beneficiary numbers in the document and not flag them as PHI..</param>
        /// <param name="allowHealthPaymentsMadeForTreatment">Set to true to allow payments made for medical treatment in the document and not flag them as PHI..</param>
        /// <param name="allowFaces">Set to true to allow identifiable human faces in the document and not flag them as PII..</param>
        /// <param name="allowVehicleID">Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the document and not flag them as PII..</param>
        /// <param name="allowDeviceID">Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the document and not flag them as PII..</param>
        /// <param name="allowNamesOfRelatives">Set to true to allow names of relatives in the document and not flag them as PII..</param>
        /// <param name="allowHealthUniversalRecordLocator">Set to true to allow health universal record locators (URLs) in the document and not flag them as PHI..</param>
        /// <param name="allowBiometrics">Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the document and not flag them as PII..</param>
        /// <param name="provideAnalysisRationale">Set to true to include a natural language rationale explaining why each detection conclusion was formed..</param>
        public DlpAdvancedDocumentDetectionRequest(byte[] inputFile = default(byte[]), string fileName = default(string), string recognitionMode = default(string), bool? allowEmailAddress = default(bool?), bool? allowPhoneNumber = default(bool?), bool? allowStreetAddress = default(bool?), bool? allowPersonName = default(bool?), bool? allowBirthDate = default(bool?), bool? allowPassportNumber = default(bool?), bool? allowDriversLicense = default(bool?), bool? allowSocialSecurityNumber = default(bool?), bool? allowTaxpayerID = default(bool?), bool? allowCreditCardNumber = default(bool?), bool? allowCreditCardExpirationDate = default(bool?), bool? allowCreditCardVerificationCode = default(bool?), bool? allowBankAccountNumber = default(bool?), bool? allowIBAN = default(bool?), bool? allowHealthInsuranceNumber = default(bool?), bool? allowBearerToken = default(bool?), bool? allowHttpCookie = default(bool?), bool? allowPrivateKeys = default(bool?), bool? allowCredentials = default(bool?), bool? allowDeepWebUrls = default(bool?), bool? allowSourceCode = default(bool?), bool? allowIpAddress = default(bool?), bool? allowMacAddress = default(bool?), bool? allowHealthInsuranceMemberID = default(bool?), bool? allowHealthInjuryOrDisease = default(bool?), bool? allowHealthTypeOfTreatment = default(bool?), bool? allowHealthDateAndTimeOfTreatment = default(bool?), bool? allowHealthPlanBeneficiaryNumber = default(bool?), bool? allowHealthPaymentsMadeForTreatment = default(bool?), bool? allowFaces = default(bool?), bool? allowVehicleID = default(bool?), bool? allowDeviceID = default(bool?), bool? allowNamesOfRelatives = default(bool?), bool? allowHealthUniversalRecordLocator = default(bool?), bool? allowBiometrics = default(bool?), bool? provideAnalysisRationale = default(bool?))
        {
            this.InputFile = inputFile;
            this.FileName = fileName;
            this.RecognitionMode = recognitionMode;
            this.AllowEmailAddress = allowEmailAddress;
            this.AllowPhoneNumber = allowPhoneNumber;
            this.AllowStreetAddress = allowStreetAddress;
            this.AllowPersonName = allowPersonName;
            this.AllowBirthDate = allowBirthDate;
            this.AllowPassportNumber = allowPassportNumber;
            this.AllowDriversLicense = allowDriversLicense;
            this.AllowSocialSecurityNumber = allowSocialSecurityNumber;
            this.AllowTaxpayerID = allowTaxpayerID;
            this.AllowCreditCardNumber = allowCreditCardNumber;
            this.AllowCreditCardExpirationDate = allowCreditCardExpirationDate;
            this.AllowCreditCardVerificationCode = allowCreditCardVerificationCode;
            this.AllowBankAccountNumber = allowBankAccountNumber;
            this.AllowIBAN = allowIBAN;
            this.AllowHealthInsuranceNumber = allowHealthInsuranceNumber;
            this.AllowBearerToken = allowBearerToken;
            this.AllowHttpCookie = allowHttpCookie;
            this.AllowPrivateKeys = allowPrivateKeys;
            this.AllowCredentials = allowCredentials;
            this.AllowDeepWebUrls = allowDeepWebUrls;
            this.AllowSourceCode = allowSourceCode;
            this.AllowIpAddress = allowIpAddress;
            this.AllowMacAddress = allowMacAddress;
            this.AllowHealthInsuranceMemberID = allowHealthInsuranceMemberID;
            this.AllowHealthInjuryOrDisease = allowHealthInjuryOrDisease;
            this.AllowHealthTypeOfTreatment = allowHealthTypeOfTreatment;
            this.AllowHealthDateAndTimeOfTreatment = allowHealthDateAndTimeOfTreatment;
            this.AllowHealthPlanBeneficiaryNumber = allowHealthPlanBeneficiaryNumber;
            this.AllowHealthPaymentsMadeForTreatment = allowHealthPaymentsMadeForTreatment;
            this.AllowFaces = allowFaces;
            this.AllowVehicleID = allowVehicleID;
            this.AllowDeviceID = allowDeviceID;
            this.AllowNamesOfRelatives = allowNamesOfRelatives;
            this.AllowHealthUniversalRecordLocator = allowHealthUniversalRecordLocator;
            this.AllowBiometrics = allowBiometrics;
            this.ProvideAnalysisRationale = provideAnalysisRationale;
        }
        
        /// <summary>
        /// Document file bytes (PDF, DOCX, PNG, or JPG) to scan for PII and sensitive data.
        /// </summary>
        /// <value>Document file bytes (PDF, DOCX, PNG, or JPG) to scan for PII and sensitive data.</value>
        [DataMember(Name="InputFile", EmitDefaultValue=false)]
        public byte[] InputFile { get; set; }

        /// <summary>
        /// Optional. Name of the input file including extension, used for format detection. If not provided, format is detected from file contents.
        /// </summary>
        /// <value>Optional. Name of the input file including extension, used for format detection. If not provided, format is detected from file contents.</value>
        [DataMember(Name="FileName", EmitDefaultValue=false)]
        public string FileName { get; set; }

        /// <summary>
        /// Optional. Recognition mode for image processing. Options: null (default), \&quot;Fast\&quot;, \&quot;FastPlus\&quot;, \&quot;FastMini\&quot;.
        /// </summary>
        /// <value>Optional. Recognition mode for image processing. Options: null (default), \&quot;Fast\&quot;, \&quot;FastPlus\&quot;, \&quot;FastMini\&quot;.</value>
        [DataMember(Name="RecognitionMode", EmitDefaultValue=false)]
        public string RecognitionMode { get; set; }

        /// <summary>
        /// Set to true to allow email addresses in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow email addresses in the document and not flag them as PII.</value>
        [DataMember(Name="AllowEmailAddress", EmitDefaultValue=false)]
        public bool? AllowEmailAddress { get; set; }

        /// <summary>
        /// Set to true to allow phone numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow phone numbers in the document and not flag them as PII.</value>
        [DataMember(Name="AllowPhoneNumber", EmitDefaultValue=false)]
        public bool? AllowPhoneNumber { get; set; }

        /// <summary>
        /// Set to true to allow street addresses in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow street addresses in the document and not flag them as PII.</value>
        [DataMember(Name="AllowStreetAddress", EmitDefaultValue=false)]
        public bool? AllowStreetAddress { get; set; }

        /// <summary>
        /// Set to true to allow person names in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow person names in the document and not flag them as PII.</value>
        [DataMember(Name="AllowPersonName", EmitDefaultValue=false)]
        public bool? AllowPersonName { get; set; }

        /// <summary>
        /// Set to true to allow birth dates in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow birth dates in the document and not flag them as PII.</value>
        [DataMember(Name="AllowBirthDate", EmitDefaultValue=false)]
        public bool? AllowBirthDate { get; set; }

        /// <summary>
        /// Set to true to allow passport numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow passport numbers in the document and not flag them as PII.</value>
        [DataMember(Name="AllowPassportNumber", EmitDefaultValue=false)]
        public bool? AllowPassportNumber { get; set; }

        /// <summary>
        /// Set to true to allow drivers license numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow drivers license numbers in the document and not flag them as PII.</value>
        [DataMember(Name="AllowDriversLicense", EmitDefaultValue=false)]
        public bool? AllowDriversLicense { get; set; }

        /// <summary>
        /// Set to true to allow social security numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow social security numbers in the document and not flag them as PII.</value>
        [DataMember(Name="AllowSocialSecurityNumber", EmitDefaultValue=false)]
        public bool? AllowSocialSecurityNumber { get; set; }

        /// <summary>
        /// Set to true to allow taxpayer IDs in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow taxpayer IDs in the document and not flag them as PII.</value>
        [DataMember(Name="AllowTaxpayerID", EmitDefaultValue=false)]
        public bool? AllowTaxpayerID { get; set; }

        /// <summary>
        /// Set to true to allow credit card numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credit card numbers in the document and not flag them as PII.</value>
        [DataMember(Name="AllowCreditCardNumber", EmitDefaultValue=false)]
        public bool? AllowCreditCardNumber { get; set; }

        /// <summary>
        /// Set to true to allow credit card expiration dates in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credit card expiration dates in the document and not flag them as PII.</value>
        [DataMember(Name="AllowCreditCardExpirationDate", EmitDefaultValue=false)]
        public bool? AllowCreditCardExpirationDate { get; set; }

        /// <summary>
        /// Set to true to allow credit card verification codes in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credit card verification codes in the document and not flag them as PII.</value>
        [DataMember(Name="AllowCreditCardVerificationCode", EmitDefaultValue=false)]
        public bool? AllowCreditCardVerificationCode { get; set; }

        /// <summary>
        /// Set to true to allow bank account numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow bank account numbers in the document and not flag them as PII.</value>
        [DataMember(Name="AllowBankAccountNumber", EmitDefaultValue=false)]
        public bool? AllowBankAccountNumber { get; set; }

        /// <summary>
        /// Set to true to allow IBANs in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow IBANs in the document and not flag them as PII.</value>
        [DataMember(Name="AllowIBAN", EmitDefaultValue=false)]
        public bool? AllowIBAN { get; set; }

        /// <summary>
        /// Set to true to allow health insurance numbers in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow health insurance numbers in the document and not flag them as PII.</value>
        [DataMember(Name="AllowHealthInsuranceNumber", EmitDefaultValue=false)]
        public bool? AllowHealthInsuranceNumber { get; set; }

        /// <summary>
        /// Set to true to allow bearer tokens in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow bearer tokens in the document and not flag them as PII.</value>
        [DataMember(Name="AllowBearerToken", EmitDefaultValue=false)]
        public bool? AllowBearerToken { get; set; }

        /// <summary>
        /// Set to true to allow HTTP cookies in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow HTTP cookies in the document and not flag them as PII.</value>
        [DataMember(Name="AllowHttpCookie", EmitDefaultValue=false)]
        public bool? AllowHttpCookie { get; set; }

        /// <summary>
        /// Set to true to allow private keys in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow private keys in the document and not flag them as PII.</value>
        [DataMember(Name="AllowPrivateKeys", EmitDefaultValue=false)]
        public bool? AllowPrivateKeys { get; set; }

        /// <summary>
        /// Set to true to allow credentials (usernames/passwords) in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow credentials (usernames/passwords) in the document and not flag them as PII.</value>
        [DataMember(Name="AllowCredentials", EmitDefaultValue=false)]
        public bool? AllowCredentials { get; set; }

        /// <summary>
        /// Set to true to allow deep web URLs (.onion) in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow deep web URLs (.onion) in the document and not flag them as PII.</value>
        [DataMember(Name="AllowDeepWebUrls", EmitDefaultValue=false)]
        public bool? AllowDeepWebUrls { get; set; }

        /// <summary>
        /// Set to true to allow source code in the document and not flag it as sensitive data.
        /// </summary>
        /// <value>Set to true to allow source code in the document and not flag it as sensitive data.</value>
        [DataMember(Name="AllowSourceCode", EmitDefaultValue=false)]
        public bool? AllowSourceCode { get; set; }

        /// <summary>
        /// Set to true to allow IP addresses in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow IP addresses in the document and not flag them as PII.</value>
        [DataMember(Name="AllowIpAddress", EmitDefaultValue=false)]
        public bool? AllowIpAddress { get; set; }

        /// <summary>
        /// Set to true to allow MAC addresses in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow MAC addresses in the document and not flag them as PII.</value>
        [DataMember(Name="AllowMacAddress", EmitDefaultValue=false)]
        public bool? AllowMacAddress { get; set; }

        /// <summary>
        /// Set to true to allow health insurance member IDs in the document and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow health insurance member IDs in the document and not flag them as PHI.</value>
        [DataMember(Name="AllowHealthInsuranceMemberID", EmitDefaultValue=false)]
        public bool? AllowHealthInsuranceMemberID { get; set; }

        /// <summary>
        /// Set to true to allow references to injuries or diseases in the document and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow references to injuries or diseases in the document and not flag them as PHI.</value>
        [DataMember(Name="AllowHealthInjuryOrDisease", EmitDefaultValue=false)]
        public bool? AllowHealthInjuryOrDisease { get; set; }

        /// <summary>
        /// Set to true to allow references to types of medical treatment in the document and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow references to types of medical treatment in the document and not flag them as PHI.</value>
        [DataMember(Name="AllowHealthTypeOfTreatment", EmitDefaultValue=false)]
        public bool? AllowHealthTypeOfTreatment { get; set; }

        /// <summary>
        /// Set to true to allow dates and times of medical treatment in the document and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow dates and times of medical treatment in the document and not flag them as PHI.</value>
        [DataMember(Name="AllowHealthDateAndTimeOfTreatment", EmitDefaultValue=false)]
        public bool? AllowHealthDateAndTimeOfTreatment { get; set; }

        /// <summary>
        /// Set to true to allow health plan beneficiary numbers in the document and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow health plan beneficiary numbers in the document and not flag them as PHI.</value>
        [DataMember(Name="AllowHealthPlanBeneficiaryNumber", EmitDefaultValue=false)]
        public bool? AllowHealthPlanBeneficiaryNumber { get; set; }

        /// <summary>
        /// Set to true to allow payments made for medical treatment in the document and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow payments made for medical treatment in the document and not flag them as PHI.</value>
        [DataMember(Name="AllowHealthPaymentsMadeForTreatment", EmitDefaultValue=false)]
        public bool? AllowHealthPaymentsMadeForTreatment { get; set; }

        /// <summary>
        /// Set to true to allow identifiable human faces in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow identifiable human faces in the document and not flag them as PII.</value>
        [DataMember(Name="AllowFaces", EmitDefaultValue=false)]
        public bool? AllowFaces { get; set; }

        /// <summary>
        /// Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the document and not flag them as PII.</value>
        [DataMember(Name="AllowVehicleID", EmitDefaultValue=false)]
        public bool? AllowVehicleID { get; set; }

        /// <summary>
        /// Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the document and not flag them as PII.</value>
        [DataMember(Name="AllowDeviceID", EmitDefaultValue=false)]
        public bool? AllowDeviceID { get; set; }

        /// <summary>
        /// Set to true to allow names of relatives in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow names of relatives in the document and not flag them as PII.</value>
        [DataMember(Name="AllowNamesOfRelatives", EmitDefaultValue=false)]
        public bool? AllowNamesOfRelatives { get; set; }

        /// <summary>
        /// Set to true to allow health universal record locators (URLs) in the document and not flag them as PHI.
        /// </summary>
        /// <value>Set to true to allow health universal record locators (URLs) in the document and not flag them as PHI.</value>
        [DataMember(Name="AllowHealthUniversalRecordLocator", EmitDefaultValue=false)]
        public bool? AllowHealthUniversalRecordLocator { get; set; }

        /// <summary>
        /// Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the document and not flag them as PII.
        /// </summary>
        /// <value>Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the document and not flag them as PII.</value>
        [DataMember(Name="AllowBiometrics", EmitDefaultValue=false)]
        public bool? AllowBiometrics { get; set; }

        /// <summary>
        /// Set to true to include a natural language rationale explaining why each detection conclusion was formed.
        /// </summary>
        /// <value>Set to true to include a natural language rationale explaining why each detection conclusion was formed.</value>
        [DataMember(Name="ProvideAnalysisRationale", EmitDefaultValue=false)]
        public bool? ProvideAnalysisRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DlpAdvancedDocumentDetectionRequest {\n");
            sb.Append("  InputFile: ").Append(InputFile).Append("\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  RecognitionMode: ").Append(RecognitionMode).Append("\n");
            sb.Append("  AllowEmailAddress: ").Append(AllowEmailAddress).Append("\n");
            sb.Append("  AllowPhoneNumber: ").Append(AllowPhoneNumber).Append("\n");
            sb.Append("  AllowStreetAddress: ").Append(AllowStreetAddress).Append("\n");
            sb.Append("  AllowPersonName: ").Append(AllowPersonName).Append("\n");
            sb.Append("  AllowBirthDate: ").Append(AllowBirthDate).Append("\n");
            sb.Append("  AllowPassportNumber: ").Append(AllowPassportNumber).Append("\n");
            sb.Append("  AllowDriversLicense: ").Append(AllowDriversLicense).Append("\n");
            sb.Append("  AllowSocialSecurityNumber: ").Append(AllowSocialSecurityNumber).Append("\n");
            sb.Append("  AllowTaxpayerID: ").Append(AllowTaxpayerID).Append("\n");
            sb.Append("  AllowCreditCardNumber: ").Append(AllowCreditCardNumber).Append("\n");
            sb.Append("  AllowCreditCardExpirationDate: ").Append(AllowCreditCardExpirationDate).Append("\n");
            sb.Append("  AllowCreditCardVerificationCode: ").Append(AllowCreditCardVerificationCode).Append("\n");
            sb.Append("  AllowBankAccountNumber: ").Append(AllowBankAccountNumber).Append("\n");
            sb.Append("  AllowIBAN: ").Append(AllowIBAN).Append("\n");
            sb.Append("  AllowHealthInsuranceNumber: ").Append(AllowHealthInsuranceNumber).Append("\n");
            sb.Append("  AllowBearerToken: ").Append(AllowBearerToken).Append("\n");
            sb.Append("  AllowHttpCookie: ").Append(AllowHttpCookie).Append("\n");
            sb.Append("  AllowPrivateKeys: ").Append(AllowPrivateKeys).Append("\n");
            sb.Append("  AllowCredentials: ").Append(AllowCredentials).Append("\n");
            sb.Append("  AllowDeepWebUrls: ").Append(AllowDeepWebUrls).Append("\n");
            sb.Append("  AllowSourceCode: ").Append(AllowSourceCode).Append("\n");
            sb.Append("  AllowIpAddress: ").Append(AllowIpAddress).Append("\n");
            sb.Append("  AllowMacAddress: ").Append(AllowMacAddress).Append("\n");
            sb.Append("  AllowHealthInsuranceMemberID: ").Append(AllowHealthInsuranceMemberID).Append("\n");
            sb.Append("  AllowHealthInjuryOrDisease: ").Append(AllowHealthInjuryOrDisease).Append("\n");
            sb.Append("  AllowHealthTypeOfTreatment: ").Append(AllowHealthTypeOfTreatment).Append("\n");
            sb.Append("  AllowHealthDateAndTimeOfTreatment: ").Append(AllowHealthDateAndTimeOfTreatment).Append("\n");
            sb.Append("  AllowHealthPlanBeneficiaryNumber: ").Append(AllowHealthPlanBeneficiaryNumber).Append("\n");
            sb.Append("  AllowHealthPaymentsMadeForTreatment: ").Append(AllowHealthPaymentsMadeForTreatment).Append("\n");
            sb.Append("  AllowFaces: ").Append(AllowFaces).Append("\n");
            sb.Append("  AllowVehicleID: ").Append(AllowVehicleID).Append("\n");
            sb.Append("  AllowDeviceID: ").Append(AllowDeviceID).Append("\n");
            sb.Append("  AllowNamesOfRelatives: ").Append(AllowNamesOfRelatives).Append("\n");
            sb.Append("  AllowHealthUniversalRecordLocator: ").Append(AllowHealthUniversalRecordLocator).Append("\n");
            sb.Append("  AllowBiometrics: ").Append(AllowBiometrics).Append("\n");
            sb.Append("  ProvideAnalysisRationale: ").Append(ProvideAnalysisRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DlpAdvancedDocumentDetectionRequest);
        }

        /// <summary>
        /// Returns true if DlpAdvancedDocumentDetectionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DlpAdvancedDocumentDetectionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DlpAdvancedDocumentDetectionRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InputFile == input.InputFile ||
                    (this.InputFile != null &&
                    this.InputFile.Equals(input.InputFile))
                ) && 
                (
                    this.FileName == input.FileName ||
                    (this.FileName != null &&
                    this.FileName.Equals(input.FileName))
                ) && 
                (
                    this.RecognitionMode == input.RecognitionMode ||
                    (this.RecognitionMode != null &&
                    this.RecognitionMode.Equals(input.RecognitionMode))
                ) && 
                (
                    this.AllowEmailAddress == input.AllowEmailAddress ||
                    (this.AllowEmailAddress != null &&
                    this.AllowEmailAddress.Equals(input.AllowEmailAddress))
                ) && 
                (
                    this.AllowPhoneNumber == input.AllowPhoneNumber ||
                    (this.AllowPhoneNumber != null &&
                    this.AllowPhoneNumber.Equals(input.AllowPhoneNumber))
                ) && 
                (
                    this.AllowStreetAddress == input.AllowStreetAddress ||
                    (this.AllowStreetAddress != null &&
                    this.AllowStreetAddress.Equals(input.AllowStreetAddress))
                ) && 
                (
                    this.AllowPersonName == input.AllowPersonName ||
                    (this.AllowPersonName != null &&
                    this.AllowPersonName.Equals(input.AllowPersonName))
                ) && 
                (
                    this.AllowBirthDate == input.AllowBirthDate ||
                    (this.AllowBirthDate != null &&
                    this.AllowBirthDate.Equals(input.AllowBirthDate))
                ) && 
                (
                    this.AllowPassportNumber == input.AllowPassportNumber ||
                    (this.AllowPassportNumber != null &&
                    this.AllowPassportNumber.Equals(input.AllowPassportNumber))
                ) && 
                (
                    this.AllowDriversLicense == input.AllowDriversLicense ||
                    (this.AllowDriversLicense != null &&
                    this.AllowDriversLicense.Equals(input.AllowDriversLicense))
                ) && 
                (
                    this.AllowSocialSecurityNumber == input.AllowSocialSecurityNumber ||
                    (this.AllowSocialSecurityNumber != null &&
                    this.AllowSocialSecurityNumber.Equals(input.AllowSocialSecurityNumber))
                ) && 
                (
                    this.AllowTaxpayerID == input.AllowTaxpayerID ||
                    (this.AllowTaxpayerID != null &&
                    this.AllowTaxpayerID.Equals(input.AllowTaxpayerID))
                ) && 
                (
                    this.AllowCreditCardNumber == input.AllowCreditCardNumber ||
                    (this.AllowCreditCardNumber != null &&
                    this.AllowCreditCardNumber.Equals(input.AllowCreditCardNumber))
                ) && 
                (
                    this.AllowCreditCardExpirationDate == input.AllowCreditCardExpirationDate ||
                    (this.AllowCreditCardExpirationDate != null &&
                    this.AllowCreditCardExpirationDate.Equals(input.AllowCreditCardExpirationDate))
                ) && 
                (
                    this.AllowCreditCardVerificationCode == input.AllowCreditCardVerificationCode ||
                    (this.AllowCreditCardVerificationCode != null &&
                    this.AllowCreditCardVerificationCode.Equals(input.AllowCreditCardVerificationCode))
                ) && 
                (
                    this.AllowBankAccountNumber == input.AllowBankAccountNumber ||
                    (this.AllowBankAccountNumber != null &&
                    this.AllowBankAccountNumber.Equals(input.AllowBankAccountNumber))
                ) && 
                (
                    this.AllowIBAN == input.AllowIBAN ||
                    (this.AllowIBAN != null &&
                    this.AllowIBAN.Equals(input.AllowIBAN))
                ) && 
                (
                    this.AllowHealthInsuranceNumber == input.AllowHealthInsuranceNumber ||
                    (this.AllowHealthInsuranceNumber != null &&
                    this.AllowHealthInsuranceNumber.Equals(input.AllowHealthInsuranceNumber))
                ) && 
                (
                    this.AllowBearerToken == input.AllowBearerToken ||
                    (this.AllowBearerToken != null &&
                    this.AllowBearerToken.Equals(input.AllowBearerToken))
                ) && 
                (
                    this.AllowHttpCookie == input.AllowHttpCookie ||
                    (this.AllowHttpCookie != null &&
                    this.AllowHttpCookie.Equals(input.AllowHttpCookie))
                ) && 
                (
                    this.AllowPrivateKeys == input.AllowPrivateKeys ||
                    (this.AllowPrivateKeys != null &&
                    this.AllowPrivateKeys.Equals(input.AllowPrivateKeys))
                ) && 
                (
                    this.AllowCredentials == input.AllowCredentials ||
                    (this.AllowCredentials != null &&
                    this.AllowCredentials.Equals(input.AllowCredentials))
                ) && 
                (
                    this.AllowDeepWebUrls == input.AllowDeepWebUrls ||
                    (this.AllowDeepWebUrls != null &&
                    this.AllowDeepWebUrls.Equals(input.AllowDeepWebUrls))
                ) && 
                (
                    this.AllowSourceCode == input.AllowSourceCode ||
                    (this.AllowSourceCode != null &&
                    this.AllowSourceCode.Equals(input.AllowSourceCode))
                ) && 
                (
                    this.AllowIpAddress == input.AllowIpAddress ||
                    (this.AllowIpAddress != null &&
                    this.AllowIpAddress.Equals(input.AllowIpAddress))
                ) && 
                (
                    this.AllowMacAddress == input.AllowMacAddress ||
                    (this.AllowMacAddress != null &&
                    this.AllowMacAddress.Equals(input.AllowMacAddress))
                ) && 
                (
                    this.AllowHealthInsuranceMemberID == input.AllowHealthInsuranceMemberID ||
                    (this.AllowHealthInsuranceMemberID != null &&
                    this.AllowHealthInsuranceMemberID.Equals(input.AllowHealthInsuranceMemberID))
                ) && 
                (
                    this.AllowHealthInjuryOrDisease == input.AllowHealthInjuryOrDisease ||
                    (this.AllowHealthInjuryOrDisease != null &&
                    this.AllowHealthInjuryOrDisease.Equals(input.AllowHealthInjuryOrDisease))
                ) && 
                (
                    this.AllowHealthTypeOfTreatment == input.AllowHealthTypeOfTreatment ||
                    (this.AllowHealthTypeOfTreatment != null &&
                    this.AllowHealthTypeOfTreatment.Equals(input.AllowHealthTypeOfTreatment))
                ) && 
                (
                    this.AllowHealthDateAndTimeOfTreatment == input.AllowHealthDateAndTimeOfTreatment ||
                    (this.AllowHealthDateAndTimeOfTreatment != null &&
                    this.AllowHealthDateAndTimeOfTreatment.Equals(input.AllowHealthDateAndTimeOfTreatment))
                ) && 
                (
                    this.AllowHealthPlanBeneficiaryNumber == input.AllowHealthPlanBeneficiaryNumber ||
                    (this.AllowHealthPlanBeneficiaryNumber != null &&
                    this.AllowHealthPlanBeneficiaryNumber.Equals(input.AllowHealthPlanBeneficiaryNumber))
                ) && 
                (
                    this.AllowHealthPaymentsMadeForTreatment == input.AllowHealthPaymentsMadeForTreatment ||
                    (this.AllowHealthPaymentsMadeForTreatment != null &&
                    this.AllowHealthPaymentsMadeForTreatment.Equals(input.AllowHealthPaymentsMadeForTreatment))
                ) && 
                (
                    this.AllowFaces == input.AllowFaces ||
                    (this.AllowFaces != null &&
                    this.AllowFaces.Equals(input.AllowFaces))
                ) && 
                (
                    this.AllowVehicleID == input.AllowVehicleID ||
                    (this.AllowVehicleID != null &&
                    this.AllowVehicleID.Equals(input.AllowVehicleID))
                ) && 
                (
                    this.AllowDeviceID == input.AllowDeviceID ||
                    (this.AllowDeviceID != null &&
                    this.AllowDeviceID.Equals(input.AllowDeviceID))
                ) && 
                (
                    this.AllowNamesOfRelatives == input.AllowNamesOfRelatives ||
                    (this.AllowNamesOfRelatives != null &&
                    this.AllowNamesOfRelatives.Equals(input.AllowNamesOfRelatives))
                ) && 
                (
                    this.AllowHealthUniversalRecordLocator == input.AllowHealthUniversalRecordLocator ||
                    (this.AllowHealthUniversalRecordLocator != null &&
                    this.AllowHealthUniversalRecordLocator.Equals(input.AllowHealthUniversalRecordLocator))
                ) && 
                (
                    this.AllowBiometrics == input.AllowBiometrics ||
                    (this.AllowBiometrics != null &&
                    this.AllowBiometrics.Equals(input.AllowBiometrics))
                ) && 
                (
                    this.ProvideAnalysisRationale == input.ProvideAnalysisRationale ||
                    (this.ProvideAnalysisRationale != null &&
                    this.ProvideAnalysisRationale.Equals(input.ProvideAnalysisRationale))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InputFile != null)
                    hashCode = hashCode * 59 + this.InputFile.GetHashCode();
                if (this.FileName != null)
                    hashCode = hashCode * 59 + this.FileName.GetHashCode();
                if (this.RecognitionMode != null)
                    hashCode = hashCode * 59 + this.RecognitionMode.GetHashCode();
                if (this.AllowEmailAddress != null)
                    hashCode = hashCode * 59 + this.AllowEmailAddress.GetHashCode();
                if (this.AllowPhoneNumber != null)
                    hashCode = hashCode * 59 + this.AllowPhoneNumber.GetHashCode();
                if (this.AllowStreetAddress != null)
                    hashCode = hashCode * 59 + this.AllowStreetAddress.GetHashCode();
                if (this.AllowPersonName != null)
                    hashCode = hashCode * 59 + this.AllowPersonName.GetHashCode();
                if (this.AllowBirthDate != null)
                    hashCode = hashCode * 59 + this.AllowBirthDate.GetHashCode();
                if (this.AllowPassportNumber != null)
                    hashCode = hashCode * 59 + this.AllowPassportNumber.GetHashCode();
                if (this.AllowDriversLicense != null)
                    hashCode = hashCode * 59 + this.AllowDriversLicense.GetHashCode();
                if (this.AllowSocialSecurityNumber != null)
                    hashCode = hashCode * 59 + this.AllowSocialSecurityNumber.GetHashCode();
                if (this.AllowTaxpayerID != null)
                    hashCode = hashCode * 59 + this.AllowTaxpayerID.GetHashCode();
                if (this.AllowCreditCardNumber != null)
                    hashCode = hashCode * 59 + this.AllowCreditCardNumber.GetHashCode();
                if (this.AllowCreditCardExpirationDate != null)
                    hashCode = hashCode * 59 + this.AllowCreditCardExpirationDate.GetHashCode();
                if (this.AllowCreditCardVerificationCode != null)
                    hashCode = hashCode * 59 + this.AllowCreditCardVerificationCode.GetHashCode();
                if (this.AllowBankAccountNumber != null)
                    hashCode = hashCode * 59 + this.AllowBankAccountNumber.GetHashCode();
                if (this.AllowIBAN != null)
                    hashCode = hashCode * 59 + this.AllowIBAN.GetHashCode();
                if (this.AllowHealthInsuranceNumber != null)
                    hashCode = hashCode * 59 + this.AllowHealthInsuranceNumber.GetHashCode();
                if (this.AllowBearerToken != null)
                    hashCode = hashCode * 59 + this.AllowBearerToken.GetHashCode();
                if (this.AllowHttpCookie != null)
                    hashCode = hashCode * 59 + this.AllowHttpCookie.GetHashCode();
                if (this.AllowPrivateKeys != null)
                    hashCode = hashCode * 59 + this.AllowPrivateKeys.GetHashCode();
                if (this.AllowCredentials != null)
                    hashCode = hashCode * 59 + this.AllowCredentials.GetHashCode();
                if (this.AllowDeepWebUrls != null)
                    hashCode = hashCode * 59 + this.AllowDeepWebUrls.GetHashCode();
                if (this.AllowSourceCode != null)
                    hashCode = hashCode * 59 + this.AllowSourceCode.GetHashCode();
                if (this.AllowIpAddress != null)
                    hashCode = hashCode * 59 + this.AllowIpAddress.GetHashCode();
                if (this.AllowMacAddress != null)
                    hashCode = hashCode * 59 + this.AllowMacAddress.GetHashCode();
                if (this.AllowHealthInsuranceMemberID != null)
                    hashCode = hashCode * 59 + this.AllowHealthInsuranceMemberID.GetHashCode();
                if (this.AllowHealthInjuryOrDisease != null)
                    hashCode = hashCode * 59 + this.AllowHealthInjuryOrDisease.GetHashCode();
                if (this.AllowHealthTypeOfTreatment != null)
                    hashCode = hashCode * 59 + this.AllowHealthTypeOfTreatment.GetHashCode();
                if (this.AllowHealthDateAndTimeOfTreatment != null)
                    hashCode = hashCode * 59 + this.AllowHealthDateAndTimeOfTreatment.GetHashCode();
                if (this.AllowHealthPlanBeneficiaryNumber != null)
                    hashCode = hashCode * 59 + this.AllowHealthPlanBeneficiaryNumber.GetHashCode();
                if (this.AllowHealthPaymentsMadeForTreatment != null)
                    hashCode = hashCode * 59 + this.AllowHealthPaymentsMadeForTreatment.GetHashCode();
                if (this.AllowFaces != null)
                    hashCode = hashCode * 59 + this.AllowFaces.GetHashCode();
                if (this.AllowVehicleID != null)
                    hashCode = hashCode * 59 + this.AllowVehicleID.GetHashCode();
                if (this.AllowDeviceID != null)
                    hashCode = hashCode * 59 + this.AllowDeviceID.GetHashCode();
                if (this.AllowNamesOfRelatives != null)
                    hashCode = hashCode * 59 + this.AllowNamesOfRelatives.GetHashCode();
                if (this.AllowHealthUniversalRecordLocator != null)
                    hashCode = hashCode * 59 + this.AllowHealthUniversalRecordLocator.GetHashCode();
                if (this.AllowBiometrics != null)
                    hashCode = hashCode * 59 + this.AllowBiometrics.GetHashCode();
                if (this.ProvideAnalysisRationale != null)
                    hashCode = hashCode * 59 + this.ProvideAnalysisRationale.GetHashCode();
                return hashCode;
            }
        }
    }

}
