/* 
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DLP.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DLP.Model
{
    /// <summary>
    /// Request object for advanced DLP text redaction with 34 PII detection types including health-related data and configurable redaction mode.
    /// </summary>
    [DataContract]
    public partial class DlpAdvancedRedactionRequest :  IEquatable<DlpAdvancedRedactionRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpAdvancedRedactionRequest" /> class.
        /// </summary>
        /// <param name="inputText">Text to scan for PII and redact sensitive data from..</param>
        /// <param name="allowEmailAddress">Set to true to allow email addresses in the input text and not redact them..</param>
        /// <param name="allowPhoneNumber">Set to true to allow phone numbers in the input text and not redact them..</param>
        /// <param name="allowStreetAddress">Set to true to allow street addresses in the input text and not redact them..</param>
        /// <param name="allowCity">Set to true to allow standalone city names (e.g. \&quot;San Francisco\&quot;) in the input text and not redact them. Applies to city names mentioned outside of a full street address..</param>
        /// <param name="allowPersonName">Set to true to allow person names in the input text and not redact them..</param>
        /// <param name="allowBirthDate">Set to true to allow birth dates in the input text and not redact them..</param>
        /// <param name="allowPassportNumber">Set to true to allow passport numbers in the input text and not redact them..</param>
        /// <param name="allowDriversLicense">Set to true to allow drivers license numbers in the input text and not redact them..</param>
        /// <param name="allowSocialSecurityNumber">Set to true to allow social security numbers in the input text and not redact them..</param>
        /// <param name="allowTaxpayerID">Set to true to allow taxpayer IDs in the input text and not redact them..</param>
        /// <param name="allowCreditCardNumber">Set to true to allow credit card numbers in the input text and not redact them..</param>
        /// <param name="allowCreditCardExpirationDate">Set to true to allow credit card expiration dates in the input text and not redact them..</param>
        /// <param name="allowCreditCardVerificationCode">Set to true to allow credit card verification codes in the input text and not redact them..</param>
        /// <param name="allowBankAccountNumber">Set to true to allow bank account numbers in the input text and not redact them..</param>
        /// <param name="allowIBAN">Set to true to allow IBANs in the input text and not redact them..</param>
        /// <param name="allowHealthInsuranceNumber">Set to true to allow health insurance numbers in the input text and not redact them..</param>
        /// <param name="allowBearerToken">Set to true to allow bearer tokens in the input text and not redact them..</param>
        /// <param name="allowHttpCookie">Set to true to allow HTTP cookies in the input text and not redact them..</param>
        /// <param name="allowPrivateKeys">Set to true to allow private keys in the input text and not redact them..</param>
        /// <param name="allowCredentials">Set to true to allow credentials (usernames/passwords) in the input text and not redact them..</param>
        /// <param name="allowDeepWebUrls">Set to true to allow deep web URLs (.onion) in the input text and not redact them..</param>
        /// <param name="allowSourceCode">Set to true to allow source code in the input text and not redact it..</param>
        /// <param name="allowIpAddress">Set to true to allow IP addresses in the input text and not redact them..</param>
        /// <param name="allowMacAddress">Set to true to allow MAC addresses in the input text and not redact them..</param>
        /// <param name="allowHealthInsuranceMemberID">Set to true to allow health insurance member IDs in the input text and not redact them..</param>
        /// <param name="allowMedicalRecordNumber">Set to true to allow medical record numbers in the input text and not redact them..</param>
        /// <param name="allowBillingAccountNumber">Set to true to allow billing account numbers (e.g. provider/customer billing account IDs, distinct from bank account numbers) in the input text and not redact them..</param>
        /// <param name="allowHealthInjuryOrDisease">Set to true to allow references to injuries or diseases in the input text and not redact them..</param>
        /// <param name="allowHealthTypeOfTreatment">Set to true to allow references to types of medical treatment in the input text and not redact them..</param>
        /// <param name="allowHealthDateAndTimeOfTreatment">Set to true to allow dates and times of medical treatment in the input text and not redact them..</param>
        /// <param name="allowHealthPlanBeneficiaryNumber">Set to true to allow health plan beneficiary numbers in the input text and not redact them..</param>
        /// <param name="allowHealthPaymentsMadeForTreatment">Set to true to allow payments made for medical treatment in the input text and not redact them..</param>
        /// <param name="allowVehicleID">Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the input text and not redact them..</param>
        /// <param name="allowDeviceID">Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the input text and not redact them..</param>
        /// <param name="allowNamesOfRelatives">Set to true to allow names of relatives in the input text and not redact them..</param>
        /// <param name="allowHealthUniversalRecordLocator">Set to true to allow health universal record locators (URLs) in the input text and not redact them..</param>
        /// <param name="allowBiometrics">Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the input text and not redact them..</param>
        /// <param name="redactionMode">Redaction mode: \&quot;SemanticTag\&quot; (default) replaces PII with a semantic tag in square brackets (e.g. [PHONE-NUMBER]), \&quot;Delete\&quot; removes PII entirely, or \&quot;ReplaceWithAsterisk\&quot; replaces PII characters with asterisks (*)..</param>
        /// <param name="provideAnalysisRationale">Set to true to include a natural language rationale explaining why each detection conclusion was formed..</param>
        /// <param name="customPolicyID">Apply a Custom Policy for DLP Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud.</param>
        /// <param name="customFields">Optional list of caller-defined custom PII fields to detect and redact in addition  to the built-in categories. Each entry has a Title (used to derive the redaction  tag, e.g. \&quot;internal participant code\&quot; → [INTERNAL-PARTICIPANT-CODE]) and a  Description telling the redaction LLM what the field looks like. Default null..</param>
        public DlpAdvancedRedactionRequest(string inputText = default(string), bool? allowEmailAddress = default(bool?), bool? allowPhoneNumber = default(bool?), bool? allowStreetAddress = default(bool?), bool? allowCity = default(bool?), bool? allowPersonName = default(bool?), bool? allowBirthDate = default(bool?), bool? allowPassportNumber = default(bool?), bool? allowDriversLicense = default(bool?), bool? allowSocialSecurityNumber = default(bool?), bool? allowTaxpayerID = default(bool?), bool? allowCreditCardNumber = default(bool?), bool? allowCreditCardExpirationDate = default(bool?), bool? allowCreditCardVerificationCode = default(bool?), bool? allowBankAccountNumber = default(bool?), bool? allowIBAN = default(bool?), bool? allowHealthInsuranceNumber = default(bool?), bool? allowBearerToken = default(bool?), bool? allowHttpCookie = default(bool?), bool? allowPrivateKeys = default(bool?), bool? allowCredentials = default(bool?), bool? allowDeepWebUrls = default(bool?), bool? allowSourceCode = default(bool?), bool? allowIpAddress = default(bool?), bool? allowMacAddress = default(bool?), bool? allowHealthInsuranceMemberID = default(bool?), bool? allowMedicalRecordNumber = default(bool?), bool? allowBillingAccountNumber = default(bool?), bool? allowHealthInjuryOrDisease = default(bool?), bool? allowHealthTypeOfTreatment = default(bool?), bool? allowHealthDateAndTimeOfTreatment = default(bool?), bool? allowHealthPlanBeneficiaryNumber = default(bool?), bool? allowHealthPaymentsMadeForTreatment = default(bool?), bool? allowVehicleID = default(bool?), bool? allowDeviceID = default(bool?), bool? allowNamesOfRelatives = default(bool?), bool? allowHealthUniversalRecordLocator = default(bool?), bool? allowBiometrics = default(bool?), string redactionMode = default(string), bool? provideAnalysisRationale = default(bool?), string customPolicyID = default(string), List<CustomPiiField> customFields = default(List<CustomPiiField>))
        {
            this.InputText = inputText;
            this.AllowEmailAddress = allowEmailAddress;
            this.AllowPhoneNumber = allowPhoneNumber;
            this.AllowStreetAddress = allowStreetAddress;
            this.AllowCity = allowCity;
            this.AllowPersonName = allowPersonName;
            this.AllowBirthDate = allowBirthDate;
            this.AllowPassportNumber = allowPassportNumber;
            this.AllowDriversLicense = allowDriversLicense;
            this.AllowSocialSecurityNumber = allowSocialSecurityNumber;
            this.AllowTaxpayerID = allowTaxpayerID;
            this.AllowCreditCardNumber = allowCreditCardNumber;
            this.AllowCreditCardExpirationDate = allowCreditCardExpirationDate;
            this.AllowCreditCardVerificationCode = allowCreditCardVerificationCode;
            this.AllowBankAccountNumber = allowBankAccountNumber;
            this.AllowIBAN = allowIBAN;
            this.AllowHealthInsuranceNumber = allowHealthInsuranceNumber;
            this.AllowBearerToken = allowBearerToken;
            this.AllowHttpCookie = allowHttpCookie;
            this.AllowPrivateKeys = allowPrivateKeys;
            this.AllowCredentials = allowCredentials;
            this.AllowDeepWebUrls = allowDeepWebUrls;
            this.AllowSourceCode = allowSourceCode;
            this.AllowIpAddress = allowIpAddress;
            this.AllowMacAddress = allowMacAddress;
            this.AllowHealthInsuranceMemberID = allowHealthInsuranceMemberID;
            this.AllowMedicalRecordNumber = allowMedicalRecordNumber;
            this.AllowBillingAccountNumber = allowBillingAccountNumber;
            this.AllowHealthInjuryOrDisease = allowHealthInjuryOrDisease;
            this.AllowHealthTypeOfTreatment = allowHealthTypeOfTreatment;
            this.AllowHealthDateAndTimeOfTreatment = allowHealthDateAndTimeOfTreatment;
            this.AllowHealthPlanBeneficiaryNumber = allowHealthPlanBeneficiaryNumber;
            this.AllowHealthPaymentsMadeForTreatment = allowHealthPaymentsMadeForTreatment;
            this.AllowVehicleID = allowVehicleID;
            this.AllowDeviceID = allowDeviceID;
            this.AllowNamesOfRelatives = allowNamesOfRelatives;
            this.AllowHealthUniversalRecordLocator = allowHealthUniversalRecordLocator;
            this.AllowBiometrics = allowBiometrics;
            this.RedactionMode = redactionMode;
            this.ProvideAnalysisRationale = provideAnalysisRationale;
            this.CustomPolicyID = customPolicyID;
            this.CustomFields = customFields;
        }
        
        /// <summary>
        /// Text to scan for PII and redact sensitive data from.
        /// </summary>
        /// <value>Text to scan for PII and redact sensitive data from.</value>
        [DataMember(Name="InputText", EmitDefaultValue=false)]
        public string InputText { get; set; }

        /// <summary>
        /// Set to true to allow email addresses in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow email addresses in the input text and not redact them.</value>
        [DataMember(Name="AllowEmailAddress", EmitDefaultValue=false)]
        public bool? AllowEmailAddress { get; set; }

        /// <summary>
        /// Set to true to allow phone numbers in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow phone numbers in the input text and not redact them.</value>
        [DataMember(Name="AllowPhoneNumber", EmitDefaultValue=false)]
        public bool? AllowPhoneNumber { get; set; }

        /// <summary>
        /// Set to true to allow street addresses in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow street addresses in the input text and not redact them.</value>
        [DataMember(Name="AllowStreetAddress", EmitDefaultValue=false)]
        public bool? AllowStreetAddress { get; set; }

        /// <summary>
        /// Set to true to allow standalone city names (e.g. \&quot;San Francisco\&quot;) in the input text and not redact them. Applies to city names mentioned outside of a full street address.
        /// </summary>
        /// <value>Set to true to allow standalone city names (e.g. \&quot;San Francisco\&quot;) in the input text and not redact them. Applies to city names mentioned outside of a full street address.</value>
        [DataMember(Name="AllowCity", EmitDefaultValue=false)]
        public bool? AllowCity { get; set; }

        /// <summary>
        /// Set to true to allow person names in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow person names in the input text and not redact them.</value>
        [DataMember(Name="AllowPersonName", EmitDefaultValue=false)]
        public bool? AllowPersonName { get; set; }

        /// <summary>
        /// Set to true to allow birth dates in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow birth dates in the input text and not redact them.</value>
        [DataMember(Name="AllowBirthDate", EmitDefaultValue=false)]
        public bool? AllowBirthDate { get; set; }

        /// <summary>
        /// Set to true to allow passport numbers in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow passport numbers in the input text and not redact them.</value>
        [DataMember(Name="AllowPassportNumber", EmitDefaultValue=false)]
        public bool? AllowPassportNumber { get; set; }

        /// <summary>
        /// Set to true to allow drivers license numbers in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow drivers license numbers in the input text and not redact them.</value>
        [DataMember(Name="AllowDriversLicense", EmitDefaultValue=false)]
        public bool? AllowDriversLicense { get; set; }

        /// <summary>
        /// Set to true to allow social security numbers in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow social security numbers in the input text and not redact them.</value>
        [DataMember(Name="AllowSocialSecurityNumber", EmitDefaultValue=false)]
        public bool? AllowSocialSecurityNumber { get; set; }

        /// <summary>
        /// Set to true to allow taxpayer IDs in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow taxpayer IDs in the input text and not redact them.</value>
        [DataMember(Name="AllowTaxpayerID", EmitDefaultValue=false)]
        public bool? AllowTaxpayerID { get; set; }

        /// <summary>
        /// Set to true to allow credit card numbers in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow credit card numbers in the input text and not redact them.</value>
        [DataMember(Name="AllowCreditCardNumber", EmitDefaultValue=false)]
        public bool? AllowCreditCardNumber { get; set; }

        /// <summary>
        /// Set to true to allow credit card expiration dates in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow credit card expiration dates in the input text and not redact them.</value>
        [DataMember(Name="AllowCreditCardExpirationDate", EmitDefaultValue=false)]
        public bool? AllowCreditCardExpirationDate { get; set; }

        /// <summary>
        /// Set to true to allow credit card verification codes in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow credit card verification codes in the input text and not redact them.</value>
        [DataMember(Name="AllowCreditCardVerificationCode", EmitDefaultValue=false)]
        public bool? AllowCreditCardVerificationCode { get; set; }

        /// <summary>
        /// Set to true to allow bank account numbers in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow bank account numbers in the input text and not redact them.</value>
        [DataMember(Name="AllowBankAccountNumber", EmitDefaultValue=false)]
        public bool? AllowBankAccountNumber { get; set; }

        /// <summary>
        /// Set to true to allow IBANs in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow IBANs in the input text and not redact them.</value>
        [DataMember(Name="AllowIBAN", EmitDefaultValue=false)]
        public bool? AllowIBAN { get; set; }

        /// <summary>
        /// Set to true to allow health insurance numbers in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow health insurance numbers in the input text and not redact them.</value>
        [DataMember(Name="AllowHealthInsuranceNumber", EmitDefaultValue=false)]
        public bool? AllowHealthInsuranceNumber { get; set; }

        /// <summary>
        /// Set to true to allow bearer tokens in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow bearer tokens in the input text and not redact them.</value>
        [DataMember(Name="AllowBearerToken", EmitDefaultValue=false)]
        public bool? AllowBearerToken { get; set; }

        /// <summary>
        /// Set to true to allow HTTP cookies in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow HTTP cookies in the input text and not redact them.</value>
        [DataMember(Name="AllowHttpCookie", EmitDefaultValue=false)]
        public bool? AllowHttpCookie { get; set; }

        /// <summary>
        /// Set to true to allow private keys in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow private keys in the input text and not redact them.</value>
        [DataMember(Name="AllowPrivateKeys", EmitDefaultValue=false)]
        public bool? AllowPrivateKeys { get; set; }

        /// <summary>
        /// Set to true to allow credentials (usernames/passwords) in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow credentials (usernames/passwords) in the input text and not redact them.</value>
        [DataMember(Name="AllowCredentials", EmitDefaultValue=false)]
        public bool? AllowCredentials { get; set; }

        /// <summary>
        /// Set to true to allow deep web URLs (.onion) in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow deep web URLs (.onion) in the input text and not redact them.</value>
        [DataMember(Name="AllowDeepWebUrls", EmitDefaultValue=false)]
        public bool? AllowDeepWebUrls { get; set; }

        /// <summary>
        /// Set to true to allow source code in the input text and not redact it.
        /// </summary>
        /// <value>Set to true to allow source code in the input text and not redact it.</value>
        [DataMember(Name="AllowSourceCode", EmitDefaultValue=false)]
        public bool? AllowSourceCode { get; set; }

        /// <summary>
        /// Set to true to allow IP addresses in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow IP addresses in the input text and not redact them.</value>
        [DataMember(Name="AllowIpAddress", EmitDefaultValue=false)]
        public bool? AllowIpAddress { get; set; }

        /// <summary>
        /// Set to true to allow MAC addresses in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow MAC addresses in the input text and not redact them.</value>
        [DataMember(Name="AllowMacAddress", EmitDefaultValue=false)]
        public bool? AllowMacAddress { get; set; }

        /// <summary>
        /// Set to true to allow health insurance member IDs in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow health insurance member IDs in the input text and not redact them.</value>
        [DataMember(Name="AllowHealthInsuranceMemberID", EmitDefaultValue=false)]
        public bool? AllowHealthInsuranceMemberID { get; set; }

        /// <summary>
        /// Set to true to allow medical record numbers in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow medical record numbers in the input text and not redact them.</value>
        [DataMember(Name="AllowMedicalRecordNumber", EmitDefaultValue=false)]
        public bool? AllowMedicalRecordNumber { get; set; }

        /// <summary>
        /// Set to true to allow billing account numbers (e.g. provider/customer billing account IDs, distinct from bank account numbers) in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow billing account numbers (e.g. provider/customer billing account IDs, distinct from bank account numbers) in the input text and not redact them.</value>
        [DataMember(Name="AllowBillingAccountNumber", EmitDefaultValue=false)]
        public bool? AllowBillingAccountNumber { get; set; }

        /// <summary>
        /// Set to true to allow references to injuries or diseases in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow references to injuries or diseases in the input text and not redact them.</value>
        [DataMember(Name="AllowHealthInjuryOrDisease", EmitDefaultValue=false)]
        public bool? AllowHealthInjuryOrDisease { get; set; }

        /// <summary>
        /// Set to true to allow references to types of medical treatment in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow references to types of medical treatment in the input text and not redact them.</value>
        [DataMember(Name="AllowHealthTypeOfTreatment", EmitDefaultValue=false)]
        public bool? AllowHealthTypeOfTreatment { get; set; }

        /// <summary>
        /// Set to true to allow dates and times of medical treatment in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow dates and times of medical treatment in the input text and not redact them.</value>
        [DataMember(Name="AllowHealthDateAndTimeOfTreatment", EmitDefaultValue=false)]
        public bool? AllowHealthDateAndTimeOfTreatment { get; set; }

        /// <summary>
        /// Set to true to allow health plan beneficiary numbers in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow health plan beneficiary numbers in the input text and not redact them.</value>
        [DataMember(Name="AllowHealthPlanBeneficiaryNumber", EmitDefaultValue=false)]
        public bool? AllowHealthPlanBeneficiaryNumber { get; set; }

        /// <summary>
        /// Set to true to allow payments made for medical treatment in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow payments made for medical treatment in the input text and not redact them.</value>
        [DataMember(Name="AllowHealthPaymentsMadeForTreatment", EmitDefaultValue=false)]
        public bool? AllowHealthPaymentsMadeForTreatment { get; set; }

        /// <summary>
        /// Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the input text and not redact them.</value>
        [DataMember(Name="AllowVehicleID", EmitDefaultValue=false)]
        public bool? AllowVehicleID { get; set; }

        /// <summary>
        /// Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the input text and not redact them.</value>
        [DataMember(Name="AllowDeviceID", EmitDefaultValue=false)]
        public bool? AllowDeviceID { get; set; }

        /// <summary>
        /// Set to true to allow names of relatives in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow names of relatives in the input text and not redact them.</value>
        [DataMember(Name="AllowNamesOfRelatives", EmitDefaultValue=false)]
        public bool? AllowNamesOfRelatives { get; set; }

        /// <summary>
        /// Set to true to allow health universal record locators (URLs) in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow health universal record locators (URLs) in the input text and not redact them.</value>
        [DataMember(Name="AllowHealthUniversalRecordLocator", EmitDefaultValue=false)]
        public bool? AllowHealthUniversalRecordLocator { get; set; }

        /// <summary>
        /// Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the input text and not redact them.
        /// </summary>
        /// <value>Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the input text and not redact them.</value>
        [DataMember(Name="AllowBiometrics", EmitDefaultValue=false)]
        public bool? AllowBiometrics { get; set; }

        /// <summary>
        /// Redaction mode: \&quot;SemanticTag\&quot; (default) replaces PII with a semantic tag in square brackets (e.g. [PHONE-NUMBER]), \&quot;Delete\&quot; removes PII entirely, or \&quot;ReplaceWithAsterisk\&quot; replaces PII characters with asterisks (*).
        /// </summary>
        /// <value>Redaction mode: \&quot;SemanticTag\&quot; (default) replaces PII with a semantic tag in square brackets (e.g. [PHONE-NUMBER]), \&quot;Delete\&quot; removes PII entirely, or \&quot;ReplaceWithAsterisk\&quot; replaces PII characters with asterisks (*).</value>
        [DataMember(Name="RedactionMode", EmitDefaultValue=false)]
        public string RedactionMode { get; set; }

        /// <summary>
        /// Set to true to include a natural language rationale explaining why each detection conclusion was formed.
        /// </summary>
        /// <value>Set to true to include a natural language rationale explaining why each detection conclusion was formed.</value>
        [DataMember(Name="ProvideAnalysisRationale", EmitDefaultValue=false)]
        public bool? ProvideAnalysisRationale { get; set; }

        /// <summary>
        /// Apply a Custom Policy for DLP Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
        /// </summary>
        /// <value>Apply a Custom Policy for DLP Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud</value>
        [DataMember(Name="CustomPolicyID", EmitDefaultValue=false)]
        public string CustomPolicyID { get; set; }

        /// <summary>
        /// Optional list of caller-defined custom PII fields to detect and redact in addition  to the built-in categories. Each entry has a Title (used to derive the redaction  tag, e.g. \&quot;internal participant code\&quot; → [INTERNAL-PARTICIPANT-CODE]) and a  Description telling the redaction LLM what the field looks like. Default null.
        /// </summary>
        /// <value>Optional list of caller-defined custom PII fields to detect and redact in addition  to the built-in categories. Each entry has a Title (used to derive the redaction  tag, e.g. \&quot;internal participant code\&quot; → [INTERNAL-PARTICIPANT-CODE]) and a  Description telling the redaction LLM what the field looks like. Default null.</value>
        [DataMember(Name="CustomFields", EmitDefaultValue=false)]
        public List<CustomPiiField> CustomFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DlpAdvancedRedactionRequest {\n");
            sb.Append("  InputText: ").Append(InputText).Append("\n");
            sb.Append("  AllowEmailAddress: ").Append(AllowEmailAddress).Append("\n");
            sb.Append("  AllowPhoneNumber: ").Append(AllowPhoneNumber).Append("\n");
            sb.Append("  AllowStreetAddress: ").Append(AllowStreetAddress).Append("\n");
            sb.Append("  AllowCity: ").Append(AllowCity).Append("\n");
            sb.Append("  AllowPersonName: ").Append(AllowPersonName).Append("\n");
            sb.Append("  AllowBirthDate: ").Append(AllowBirthDate).Append("\n");
            sb.Append("  AllowPassportNumber: ").Append(AllowPassportNumber).Append("\n");
            sb.Append("  AllowDriversLicense: ").Append(AllowDriversLicense).Append("\n");
            sb.Append("  AllowSocialSecurityNumber: ").Append(AllowSocialSecurityNumber).Append("\n");
            sb.Append("  AllowTaxpayerID: ").Append(AllowTaxpayerID).Append("\n");
            sb.Append("  AllowCreditCardNumber: ").Append(AllowCreditCardNumber).Append("\n");
            sb.Append("  AllowCreditCardExpirationDate: ").Append(AllowCreditCardExpirationDate).Append("\n");
            sb.Append("  AllowCreditCardVerificationCode: ").Append(AllowCreditCardVerificationCode).Append("\n");
            sb.Append("  AllowBankAccountNumber: ").Append(AllowBankAccountNumber).Append("\n");
            sb.Append("  AllowIBAN: ").Append(AllowIBAN).Append("\n");
            sb.Append("  AllowHealthInsuranceNumber: ").Append(AllowHealthInsuranceNumber).Append("\n");
            sb.Append("  AllowBearerToken: ").Append(AllowBearerToken).Append("\n");
            sb.Append("  AllowHttpCookie: ").Append(AllowHttpCookie).Append("\n");
            sb.Append("  AllowPrivateKeys: ").Append(AllowPrivateKeys).Append("\n");
            sb.Append("  AllowCredentials: ").Append(AllowCredentials).Append("\n");
            sb.Append("  AllowDeepWebUrls: ").Append(AllowDeepWebUrls).Append("\n");
            sb.Append("  AllowSourceCode: ").Append(AllowSourceCode).Append("\n");
            sb.Append("  AllowIpAddress: ").Append(AllowIpAddress).Append("\n");
            sb.Append("  AllowMacAddress: ").Append(AllowMacAddress).Append("\n");
            sb.Append("  AllowHealthInsuranceMemberID: ").Append(AllowHealthInsuranceMemberID).Append("\n");
            sb.Append("  AllowMedicalRecordNumber: ").Append(AllowMedicalRecordNumber).Append("\n");
            sb.Append("  AllowBillingAccountNumber: ").Append(AllowBillingAccountNumber).Append("\n");
            sb.Append("  AllowHealthInjuryOrDisease: ").Append(AllowHealthInjuryOrDisease).Append("\n");
            sb.Append("  AllowHealthTypeOfTreatment: ").Append(AllowHealthTypeOfTreatment).Append("\n");
            sb.Append("  AllowHealthDateAndTimeOfTreatment: ").Append(AllowHealthDateAndTimeOfTreatment).Append("\n");
            sb.Append("  AllowHealthPlanBeneficiaryNumber: ").Append(AllowHealthPlanBeneficiaryNumber).Append("\n");
            sb.Append("  AllowHealthPaymentsMadeForTreatment: ").Append(AllowHealthPaymentsMadeForTreatment).Append("\n");
            sb.Append("  AllowVehicleID: ").Append(AllowVehicleID).Append("\n");
            sb.Append("  AllowDeviceID: ").Append(AllowDeviceID).Append("\n");
            sb.Append("  AllowNamesOfRelatives: ").Append(AllowNamesOfRelatives).Append("\n");
            sb.Append("  AllowHealthUniversalRecordLocator: ").Append(AllowHealthUniversalRecordLocator).Append("\n");
            sb.Append("  AllowBiometrics: ").Append(AllowBiometrics).Append("\n");
            sb.Append("  RedactionMode: ").Append(RedactionMode).Append("\n");
            sb.Append("  ProvideAnalysisRationale: ").Append(ProvideAnalysisRationale).Append("\n");
            sb.Append("  CustomPolicyID: ").Append(CustomPolicyID).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DlpAdvancedRedactionRequest);
        }

        /// <summary>
        /// Returns true if DlpAdvancedRedactionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DlpAdvancedRedactionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DlpAdvancedRedactionRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InputText == input.InputText ||
                    (this.InputText != null &&
                    this.InputText.Equals(input.InputText))
                ) && 
                (
                    this.AllowEmailAddress == input.AllowEmailAddress ||
                    (this.AllowEmailAddress != null &&
                    this.AllowEmailAddress.Equals(input.AllowEmailAddress))
                ) && 
                (
                    this.AllowPhoneNumber == input.AllowPhoneNumber ||
                    (this.AllowPhoneNumber != null &&
                    this.AllowPhoneNumber.Equals(input.AllowPhoneNumber))
                ) && 
                (
                    this.AllowStreetAddress == input.AllowStreetAddress ||
                    (this.AllowStreetAddress != null &&
                    this.AllowStreetAddress.Equals(input.AllowStreetAddress))
                ) && 
                (
                    this.AllowCity == input.AllowCity ||
                    (this.AllowCity != null &&
                    this.AllowCity.Equals(input.AllowCity))
                ) && 
                (
                    this.AllowPersonName == input.AllowPersonName ||
                    (this.AllowPersonName != null &&
                    this.AllowPersonName.Equals(input.AllowPersonName))
                ) && 
                (
                    this.AllowBirthDate == input.AllowBirthDate ||
                    (this.AllowBirthDate != null &&
                    this.AllowBirthDate.Equals(input.AllowBirthDate))
                ) && 
                (
                    this.AllowPassportNumber == input.AllowPassportNumber ||
                    (this.AllowPassportNumber != null &&
                    this.AllowPassportNumber.Equals(input.AllowPassportNumber))
                ) && 
                (
                    this.AllowDriversLicense == input.AllowDriversLicense ||
                    (this.AllowDriversLicense != null &&
                    this.AllowDriversLicense.Equals(input.AllowDriversLicense))
                ) && 
                (
                    this.AllowSocialSecurityNumber == input.AllowSocialSecurityNumber ||
                    (this.AllowSocialSecurityNumber != null &&
                    this.AllowSocialSecurityNumber.Equals(input.AllowSocialSecurityNumber))
                ) && 
                (
                    this.AllowTaxpayerID == input.AllowTaxpayerID ||
                    (this.AllowTaxpayerID != null &&
                    this.AllowTaxpayerID.Equals(input.AllowTaxpayerID))
                ) && 
                (
                    this.AllowCreditCardNumber == input.AllowCreditCardNumber ||
                    (this.AllowCreditCardNumber != null &&
                    this.AllowCreditCardNumber.Equals(input.AllowCreditCardNumber))
                ) && 
                (
                    this.AllowCreditCardExpirationDate == input.AllowCreditCardExpirationDate ||
                    (this.AllowCreditCardExpirationDate != null &&
                    this.AllowCreditCardExpirationDate.Equals(input.AllowCreditCardExpirationDate))
                ) && 
                (
                    this.AllowCreditCardVerificationCode == input.AllowCreditCardVerificationCode ||
                    (this.AllowCreditCardVerificationCode != null &&
                    this.AllowCreditCardVerificationCode.Equals(input.AllowCreditCardVerificationCode))
                ) && 
                (
                    this.AllowBankAccountNumber == input.AllowBankAccountNumber ||
                    (this.AllowBankAccountNumber != null &&
                    this.AllowBankAccountNumber.Equals(input.AllowBankAccountNumber))
                ) && 
                (
                    this.AllowIBAN == input.AllowIBAN ||
                    (this.AllowIBAN != null &&
                    this.AllowIBAN.Equals(input.AllowIBAN))
                ) && 
                (
                    this.AllowHealthInsuranceNumber == input.AllowHealthInsuranceNumber ||
                    (this.AllowHealthInsuranceNumber != null &&
                    this.AllowHealthInsuranceNumber.Equals(input.AllowHealthInsuranceNumber))
                ) && 
                (
                    this.AllowBearerToken == input.AllowBearerToken ||
                    (this.AllowBearerToken != null &&
                    this.AllowBearerToken.Equals(input.AllowBearerToken))
                ) && 
                (
                    this.AllowHttpCookie == input.AllowHttpCookie ||
                    (this.AllowHttpCookie != null &&
                    this.AllowHttpCookie.Equals(input.AllowHttpCookie))
                ) && 
                (
                    this.AllowPrivateKeys == input.AllowPrivateKeys ||
                    (this.AllowPrivateKeys != null &&
                    this.AllowPrivateKeys.Equals(input.AllowPrivateKeys))
                ) && 
                (
                    this.AllowCredentials == input.AllowCredentials ||
                    (this.AllowCredentials != null &&
                    this.AllowCredentials.Equals(input.AllowCredentials))
                ) && 
                (
                    this.AllowDeepWebUrls == input.AllowDeepWebUrls ||
                    (this.AllowDeepWebUrls != null &&
                    this.AllowDeepWebUrls.Equals(input.AllowDeepWebUrls))
                ) && 
                (
                    this.AllowSourceCode == input.AllowSourceCode ||
                    (this.AllowSourceCode != null &&
                    this.AllowSourceCode.Equals(input.AllowSourceCode))
                ) && 
                (
                    this.AllowIpAddress == input.AllowIpAddress ||
                    (this.AllowIpAddress != null &&
                    this.AllowIpAddress.Equals(input.AllowIpAddress))
                ) && 
                (
                    this.AllowMacAddress == input.AllowMacAddress ||
                    (this.AllowMacAddress != null &&
                    this.AllowMacAddress.Equals(input.AllowMacAddress))
                ) && 
                (
                    this.AllowHealthInsuranceMemberID == input.AllowHealthInsuranceMemberID ||
                    (this.AllowHealthInsuranceMemberID != null &&
                    this.AllowHealthInsuranceMemberID.Equals(input.AllowHealthInsuranceMemberID))
                ) && 
                (
                    this.AllowMedicalRecordNumber == input.AllowMedicalRecordNumber ||
                    (this.AllowMedicalRecordNumber != null &&
                    this.AllowMedicalRecordNumber.Equals(input.AllowMedicalRecordNumber))
                ) && 
                (
                    this.AllowBillingAccountNumber == input.AllowBillingAccountNumber ||
                    (this.AllowBillingAccountNumber != null &&
                    this.AllowBillingAccountNumber.Equals(input.AllowBillingAccountNumber))
                ) && 
                (
                    this.AllowHealthInjuryOrDisease == input.AllowHealthInjuryOrDisease ||
                    (this.AllowHealthInjuryOrDisease != null &&
                    this.AllowHealthInjuryOrDisease.Equals(input.AllowHealthInjuryOrDisease))
                ) && 
                (
                    this.AllowHealthTypeOfTreatment == input.AllowHealthTypeOfTreatment ||
                    (this.AllowHealthTypeOfTreatment != null &&
                    this.AllowHealthTypeOfTreatment.Equals(input.AllowHealthTypeOfTreatment))
                ) && 
                (
                    this.AllowHealthDateAndTimeOfTreatment == input.AllowHealthDateAndTimeOfTreatment ||
                    (this.AllowHealthDateAndTimeOfTreatment != null &&
                    this.AllowHealthDateAndTimeOfTreatment.Equals(input.AllowHealthDateAndTimeOfTreatment))
                ) && 
                (
                    this.AllowHealthPlanBeneficiaryNumber == input.AllowHealthPlanBeneficiaryNumber ||
                    (this.AllowHealthPlanBeneficiaryNumber != null &&
                    this.AllowHealthPlanBeneficiaryNumber.Equals(input.AllowHealthPlanBeneficiaryNumber))
                ) && 
                (
                    this.AllowHealthPaymentsMadeForTreatment == input.AllowHealthPaymentsMadeForTreatment ||
                    (this.AllowHealthPaymentsMadeForTreatment != null &&
                    this.AllowHealthPaymentsMadeForTreatment.Equals(input.AllowHealthPaymentsMadeForTreatment))
                ) && 
                (
                    this.AllowVehicleID == input.AllowVehicleID ||
                    (this.AllowVehicleID != null &&
                    this.AllowVehicleID.Equals(input.AllowVehicleID))
                ) && 
                (
                    this.AllowDeviceID == input.AllowDeviceID ||
                    (this.AllowDeviceID != null &&
                    this.AllowDeviceID.Equals(input.AllowDeviceID))
                ) && 
                (
                    this.AllowNamesOfRelatives == input.AllowNamesOfRelatives ||
                    (this.AllowNamesOfRelatives != null &&
                    this.AllowNamesOfRelatives.Equals(input.AllowNamesOfRelatives))
                ) && 
                (
                    this.AllowHealthUniversalRecordLocator == input.AllowHealthUniversalRecordLocator ||
                    (this.AllowHealthUniversalRecordLocator != null &&
                    this.AllowHealthUniversalRecordLocator.Equals(input.AllowHealthUniversalRecordLocator))
                ) && 
                (
                    this.AllowBiometrics == input.AllowBiometrics ||
                    (this.AllowBiometrics != null &&
                    this.AllowBiometrics.Equals(input.AllowBiometrics))
                ) && 
                (
                    this.RedactionMode == input.RedactionMode ||
                    (this.RedactionMode != null &&
                    this.RedactionMode.Equals(input.RedactionMode))
                ) && 
                (
                    this.ProvideAnalysisRationale == input.ProvideAnalysisRationale ||
                    (this.ProvideAnalysisRationale != null &&
                    this.ProvideAnalysisRationale.Equals(input.ProvideAnalysisRationale))
                ) && 
                (
                    this.CustomPolicyID == input.CustomPolicyID ||
                    (this.CustomPolicyID != null &&
                    this.CustomPolicyID.Equals(input.CustomPolicyID))
                ) && 
                (
                    this.CustomFields == input.CustomFields ||
                    this.CustomFields != null &&
                    this.CustomFields.SequenceEqual(input.CustomFields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InputText != null)
                    hashCode = hashCode * 59 + this.InputText.GetHashCode();
                if (this.AllowEmailAddress != null)
                    hashCode = hashCode * 59 + this.AllowEmailAddress.GetHashCode();
                if (this.AllowPhoneNumber != null)
                    hashCode = hashCode * 59 + this.AllowPhoneNumber.GetHashCode();
                if (this.AllowStreetAddress != null)
                    hashCode = hashCode * 59 + this.AllowStreetAddress.GetHashCode();
                if (this.AllowCity != null)
                    hashCode = hashCode * 59 + this.AllowCity.GetHashCode();
                if (this.AllowPersonName != null)
                    hashCode = hashCode * 59 + this.AllowPersonName.GetHashCode();
                if (this.AllowBirthDate != null)
                    hashCode = hashCode * 59 + this.AllowBirthDate.GetHashCode();
                if (this.AllowPassportNumber != null)
                    hashCode = hashCode * 59 + this.AllowPassportNumber.GetHashCode();
                if (this.AllowDriversLicense != null)
                    hashCode = hashCode * 59 + this.AllowDriversLicense.GetHashCode();
                if (this.AllowSocialSecurityNumber != null)
                    hashCode = hashCode * 59 + this.AllowSocialSecurityNumber.GetHashCode();
                if (this.AllowTaxpayerID != null)
                    hashCode = hashCode * 59 + this.AllowTaxpayerID.GetHashCode();
                if (this.AllowCreditCardNumber != null)
                    hashCode = hashCode * 59 + this.AllowCreditCardNumber.GetHashCode();
                if (this.AllowCreditCardExpirationDate != null)
                    hashCode = hashCode * 59 + this.AllowCreditCardExpirationDate.GetHashCode();
                if (this.AllowCreditCardVerificationCode != null)
                    hashCode = hashCode * 59 + this.AllowCreditCardVerificationCode.GetHashCode();
                if (this.AllowBankAccountNumber != null)
                    hashCode = hashCode * 59 + this.AllowBankAccountNumber.GetHashCode();
                if (this.AllowIBAN != null)
                    hashCode = hashCode * 59 + this.AllowIBAN.GetHashCode();
                if (this.AllowHealthInsuranceNumber != null)
                    hashCode = hashCode * 59 + this.AllowHealthInsuranceNumber.GetHashCode();
                if (this.AllowBearerToken != null)
                    hashCode = hashCode * 59 + this.AllowBearerToken.GetHashCode();
                if (this.AllowHttpCookie != null)
                    hashCode = hashCode * 59 + this.AllowHttpCookie.GetHashCode();
                if (this.AllowPrivateKeys != null)
                    hashCode = hashCode * 59 + this.AllowPrivateKeys.GetHashCode();
                if (this.AllowCredentials != null)
                    hashCode = hashCode * 59 + this.AllowCredentials.GetHashCode();
                if (this.AllowDeepWebUrls != null)
                    hashCode = hashCode * 59 + this.AllowDeepWebUrls.GetHashCode();
                if (this.AllowSourceCode != null)
                    hashCode = hashCode * 59 + this.AllowSourceCode.GetHashCode();
                if (this.AllowIpAddress != null)
                    hashCode = hashCode * 59 + this.AllowIpAddress.GetHashCode();
                if (this.AllowMacAddress != null)
                    hashCode = hashCode * 59 + this.AllowMacAddress.GetHashCode();
                if (this.AllowHealthInsuranceMemberID != null)
                    hashCode = hashCode * 59 + this.AllowHealthInsuranceMemberID.GetHashCode();
                if (this.AllowMedicalRecordNumber != null)
                    hashCode = hashCode * 59 + this.AllowMedicalRecordNumber.GetHashCode();
                if (this.AllowBillingAccountNumber != null)
                    hashCode = hashCode * 59 + this.AllowBillingAccountNumber.GetHashCode();
                if (this.AllowHealthInjuryOrDisease != null)
                    hashCode = hashCode * 59 + this.AllowHealthInjuryOrDisease.GetHashCode();
                if (this.AllowHealthTypeOfTreatment != null)
                    hashCode = hashCode * 59 + this.AllowHealthTypeOfTreatment.GetHashCode();
                if (this.AllowHealthDateAndTimeOfTreatment != null)
                    hashCode = hashCode * 59 + this.AllowHealthDateAndTimeOfTreatment.GetHashCode();
                if (this.AllowHealthPlanBeneficiaryNumber != null)
                    hashCode = hashCode * 59 + this.AllowHealthPlanBeneficiaryNumber.GetHashCode();
                if (this.AllowHealthPaymentsMadeForTreatment != null)
                    hashCode = hashCode * 59 + this.AllowHealthPaymentsMadeForTreatment.GetHashCode();
                if (this.AllowVehicleID != null)
                    hashCode = hashCode * 59 + this.AllowVehicleID.GetHashCode();
                if (this.AllowDeviceID != null)
                    hashCode = hashCode * 59 + this.AllowDeviceID.GetHashCode();
                if (this.AllowNamesOfRelatives != null)
                    hashCode = hashCode * 59 + this.AllowNamesOfRelatives.GetHashCode();
                if (this.AllowHealthUniversalRecordLocator != null)
                    hashCode = hashCode * 59 + this.AllowHealthUniversalRecordLocator.GetHashCode();
                if (this.AllowBiometrics != null)
                    hashCode = hashCode * 59 + this.AllowBiometrics.GetHashCode();
                if (this.RedactionMode != null)
                    hashCode = hashCode * 59 + this.RedactionMode.GetHashCode();
                if (this.ProvideAnalysisRationale != null)
                    hashCode = hashCode * 59 + this.ProvideAnalysisRationale.GetHashCode();
                if (this.CustomPolicyID != null)
                    hashCode = hashCode * 59 + this.CustomPolicyID.GetHashCode();
                if (this.CustomFields != null)
                    hashCode = hashCode * 59 + this.CustomFields.GetHashCode();
                return hashCode;
            }
        }
    }

}
