/* 
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DLP.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DLP.Model
{
    /// <summary>
    /// Result of performing a DLP batch job operation
    /// </summary>
    [DataContract]
    public partial class DlpBatchJobStatusResult :  IEquatable<DlpBatchJobStatusResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpBatchJobStatusResult" /> class.
        /// </summary>
        /// <param name="successful">True if the operation to check the status of the job was successful, false otherwise.</param>
        /// <param name="asyncJobStatus">Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED.</param>
        /// <param name="asyncJobID">Job ID.</param>
        /// <param name="detectAudioResult">detectAudioResult.</param>
        /// <param name="detectAudioAdvancedResult">detectAudioAdvancedResult.</param>
        /// <param name="redactAudioResult">redactAudioResult.</param>
        /// <param name="redactAudioAdvancedResult">redactAudioAdvancedResult.</param>
        /// <param name="errorMessage">Error message (if any).</param>
        public DlpBatchJobStatusResult(bool? successful = default(bool?), string asyncJobStatus = default(string), string asyncJobID = default(string), DlpAudioDetectionResponse detectAudioResult = default(DlpAudioDetectionResponse), DlpAdvancedAudioDetectionResponse detectAudioAdvancedResult = default(DlpAdvancedAudioDetectionResponse), DlpAudioRedactionResponse redactAudioResult = default(DlpAudioRedactionResponse), DlpAdvancedAudioRedactionResponse redactAudioAdvancedResult = default(DlpAdvancedAudioRedactionResponse), string errorMessage = default(string))
        {
            this.Successful = successful;
            this.AsyncJobStatus = asyncJobStatus;
            this.AsyncJobID = asyncJobID;
            this.DetectAudioResult = detectAudioResult;
            this.DetectAudioAdvancedResult = detectAudioAdvancedResult;
            this.RedactAudioResult = redactAudioResult;
            this.RedactAudioAdvancedResult = redactAudioAdvancedResult;
            this.ErrorMessage = errorMessage;
        }
        
        /// <summary>
        /// True if the operation to check the status of the job was successful, false otherwise
        /// </summary>
        /// <value>True if the operation to check the status of the job was successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED
        /// </summary>
        /// <value>Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED</value>
        [DataMember(Name="AsyncJobStatus", EmitDefaultValue=false)]
        public string AsyncJobStatus { get; set; }

        /// <summary>
        /// Job ID
        /// </summary>
        /// <value>Job ID</value>
        [DataMember(Name="AsyncJobID", EmitDefaultValue=false)]
        public string AsyncJobID { get; set; }

        /// <summary>
        /// Gets or Sets DetectAudioResult
        /// </summary>
        [DataMember(Name="DetectAudioResult", EmitDefaultValue=false)]
        public DlpAudioDetectionResponse DetectAudioResult { get; set; }

        /// <summary>
        /// Gets or Sets DetectAudioAdvancedResult
        /// </summary>
        [DataMember(Name="DetectAudioAdvancedResult", EmitDefaultValue=false)]
        public DlpAdvancedAudioDetectionResponse DetectAudioAdvancedResult { get; set; }

        /// <summary>
        /// Gets or Sets RedactAudioResult
        /// </summary>
        [DataMember(Name="RedactAudioResult", EmitDefaultValue=false)]
        public DlpAudioRedactionResponse RedactAudioResult { get; set; }

        /// <summary>
        /// Gets or Sets RedactAudioAdvancedResult
        /// </summary>
        [DataMember(Name="RedactAudioAdvancedResult", EmitDefaultValue=false)]
        public DlpAdvancedAudioRedactionResponse RedactAudioAdvancedResult { get; set; }

        /// <summary>
        /// Error message (if any)
        /// </summary>
        /// <value>Error message (if any)</value>
        [DataMember(Name="ErrorMessage", EmitDefaultValue=false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DlpBatchJobStatusResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  AsyncJobStatus: ").Append(AsyncJobStatus).Append("\n");
            sb.Append("  AsyncJobID: ").Append(AsyncJobID).Append("\n");
            sb.Append("  DetectAudioResult: ").Append(DetectAudioResult).Append("\n");
            sb.Append("  DetectAudioAdvancedResult: ").Append(DetectAudioAdvancedResult).Append("\n");
            sb.Append("  RedactAudioResult: ").Append(RedactAudioResult).Append("\n");
            sb.Append("  RedactAudioAdvancedResult: ").Append(RedactAudioAdvancedResult).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DlpBatchJobStatusResult);
        }

        /// <summary>
        /// Returns true if DlpBatchJobStatusResult instances are equal
        /// </summary>
        /// <param name="input">Instance of DlpBatchJobStatusResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DlpBatchJobStatusResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.AsyncJobStatus == input.AsyncJobStatus ||
                    (this.AsyncJobStatus != null &&
                    this.AsyncJobStatus.Equals(input.AsyncJobStatus))
                ) && 
                (
                    this.AsyncJobID == input.AsyncJobID ||
                    (this.AsyncJobID != null &&
                    this.AsyncJobID.Equals(input.AsyncJobID))
                ) && 
                (
                    this.DetectAudioResult == input.DetectAudioResult ||
                    (this.DetectAudioResult != null &&
                    this.DetectAudioResult.Equals(input.DetectAudioResult))
                ) && 
                (
                    this.DetectAudioAdvancedResult == input.DetectAudioAdvancedResult ||
                    (this.DetectAudioAdvancedResult != null &&
                    this.DetectAudioAdvancedResult.Equals(input.DetectAudioAdvancedResult))
                ) && 
                (
                    this.RedactAudioResult == input.RedactAudioResult ||
                    (this.RedactAudioResult != null &&
                    this.RedactAudioResult.Equals(input.RedactAudioResult))
                ) && 
                (
                    this.RedactAudioAdvancedResult == input.RedactAudioAdvancedResult ||
                    (this.RedactAudioAdvancedResult != null &&
                    this.RedactAudioAdvancedResult.Equals(input.RedactAudioAdvancedResult))
                ) && 
                (
                    this.ErrorMessage == input.ErrorMessage ||
                    (this.ErrorMessage != null &&
                    this.ErrorMessage.Equals(input.ErrorMessage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.AsyncJobStatus != null)
                    hashCode = hashCode * 59 + this.AsyncJobStatus.GetHashCode();
                if (this.AsyncJobID != null)
                    hashCode = hashCode * 59 + this.AsyncJobID.GetHashCode();
                if (this.DetectAudioResult != null)
                    hashCode = hashCode * 59 + this.DetectAudioResult.GetHashCode();
                if (this.DetectAudioAdvancedResult != null)
                    hashCode = hashCode * 59 + this.DetectAudioAdvancedResult.GetHashCode();
                if (this.RedactAudioResult != null)
                    hashCode = hashCode * 59 + this.RedactAudioResult.GetHashCode();
                if (this.RedactAudioAdvancedResult != null)
                    hashCode = hashCode * 59 + this.RedactAudioAdvancedResult.GetHashCode();
                if (this.ErrorMessage != null)
                    hashCode = hashCode * 59 + this.ErrorMessage.GetHashCode();
                return hashCode;
            }
        }
    }

}
