/* 
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DLP.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DLP.Model
{
    /// <summary>
    /// Response object for DLP text and document detection with 23 PII detection types.
    /// </summary>
    [DataContract]
    public partial class DlpDetectionResponse :  IEquatable<DlpDetectionResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpDetectionResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found..</param>
        /// <param name="containsEmailAddress">True if the input contains email addresses..</param>
        /// <param name="containsPhoneNumber">True if the input contains phone numbers..</param>
        /// <param name="containsStreetAddress">True if the input contains street addresses..</param>
        /// <param name="containsPersonName">True if the input contains person names..</param>
        /// <param name="containsBirthDate">True if the input contains birth dates..</param>
        /// <param name="containsPassportNumber">True if the input contains passport numbers..</param>
        /// <param name="containsDriversLicense">True if the input contains drivers license numbers..</param>
        /// <param name="containsSocialSecurityNumber">True if the input contains social security numbers..</param>
        /// <param name="containsTaxpayerID">True if the input contains taxpayer IDs..</param>
        /// <param name="containsCreditCardNumber">True if the input contains credit card numbers..</param>
        /// <param name="containsCreditCardExpirationDate">True if the input contains credit card expiration dates..</param>
        /// <param name="containsCreditCardVerificationCode">True if the input contains credit card verification codes..</param>
        /// <param name="containsBankAccountNumber">True if the input contains bank account numbers..</param>
        /// <param name="containsIBAN">True if the input contains IBANs..</param>
        /// <param name="containsHealthInsuranceNumber">True if the input contains health insurance numbers..</param>
        /// <param name="containsBearerToken">True if the input contains bearer tokens..</param>
        /// <param name="containsHttpCookie">True if the input contains HTTP cookies..</param>
        /// <param name="containsPrivateKeys">True if the input contains private keys..</param>
        /// <param name="containsCredentials">True if the input contains credentials (usernames/passwords)..</param>
        /// <param name="containsDeepWebUrls">True if the input contains deep web URLs (.onion)..</param>
        /// <param name="containsSourceCode">True if the input contains source code..</param>
        /// <param name="containsIpAddress">True if the input contains IP addresses..</param>
        /// <param name="containsMacAddress">True if the input contains MAC addresses..</param>
        public DlpDetectionResponse(bool? cleanResult = default(bool?), bool? containsEmailAddress = default(bool?), bool? containsPhoneNumber = default(bool?), bool? containsStreetAddress = default(bool?), bool? containsPersonName = default(bool?), bool? containsBirthDate = default(bool?), bool? containsPassportNumber = default(bool?), bool? containsDriversLicense = default(bool?), bool? containsSocialSecurityNumber = default(bool?), bool? containsTaxpayerID = default(bool?), bool? containsCreditCardNumber = default(bool?), bool? containsCreditCardExpirationDate = default(bool?), bool? containsCreditCardVerificationCode = default(bool?), bool? containsBankAccountNumber = default(bool?), bool? containsIBAN = default(bool?), bool? containsHealthInsuranceNumber = default(bool?), bool? containsBearerToken = default(bool?), bool? containsHttpCookie = default(bool?), bool? containsPrivateKeys = default(bool?), bool? containsCredentials = default(bool?), bool? containsDeepWebUrls = default(bool?), bool? containsSourceCode = default(bool?), bool? containsIpAddress = default(bool?), bool? containsMacAddress = default(bool?))
        {
            this.CleanResult = cleanResult;
            this.ContainsEmailAddress = containsEmailAddress;
            this.ContainsPhoneNumber = containsPhoneNumber;
            this.ContainsStreetAddress = containsStreetAddress;
            this.ContainsPersonName = containsPersonName;
            this.ContainsBirthDate = containsBirthDate;
            this.ContainsPassportNumber = containsPassportNumber;
            this.ContainsDriversLicense = containsDriversLicense;
            this.ContainsSocialSecurityNumber = containsSocialSecurityNumber;
            this.ContainsTaxpayerID = containsTaxpayerID;
            this.ContainsCreditCardNumber = containsCreditCardNumber;
            this.ContainsCreditCardExpirationDate = containsCreditCardExpirationDate;
            this.ContainsCreditCardVerificationCode = containsCreditCardVerificationCode;
            this.ContainsBankAccountNumber = containsBankAccountNumber;
            this.ContainsIBAN = containsIBAN;
            this.ContainsHealthInsuranceNumber = containsHealthInsuranceNumber;
            this.ContainsBearerToken = containsBearerToken;
            this.ContainsHttpCookie = containsHttpCookie;
            this.ContainsPrivateKeys = containsPrivateKeys;
            this.ContainsCredentials = containsCredentials;
            this.ContainsDeepWebUrls = containsDeepWebUrls;
            this.ContainsSourceCode = containsSourceCode;
            this.ContainsIpAddress = containsIpAddress;
            this.ContainsMacAddress = containsMacAddress;
        }
        
        /// <summary>
        /// True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found.
        /// </summary>
        /// <value>True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found.</value>
        [DataMember(Name="CleanResult", EmitDefaultValue=false)]
        public bool? CleanResult { get; set; }

        /// <summary>
        /// True if the input contains email addresses.
        /// </summary>
        /// <value>True if the input contains email addresses.</value>
        [DataMember(Name="ContainsEmailAddress", EmitDefaultValue=false)]
        public bool? ContainsEmailAddress { get; set; }

        /// <summary>
        /// True if the input contains phone numbers.
        /// </summary>
        /// <value>True if the input contains phone numbers.</value>
        [DataMember(Name="ContainsPhoneNumber", EmitDefaultValue=false)]
        public bool? ContainsPhoneNumber { get; set; }

        /// <summary>
        /// True if the input contains street addresses.
        /// </summary>
        /// <value>True if the input contains street addresses.</value>
        [DataMember(Name="ContainsStreetAddress", EmitDefaultValue=false)]
        public bool? ContainsStreetAddress { get; set; }

        /// <summary>
        /// True if the input contains person names.
        /// </summary>
        /// <value>True if the input contains person names.</value>
        [DataMember(Name="ContainsPersonName", EmitDefaultValue=false)]
        public bool? ContainsPersonName { get; set; }

        /// <summary>
        /// True if the input contains birth dates.
        /// </summary>
        /// <value>True if the input contains birth dates.</value>
        [DataMember(Name="ContainsBirthDate", EmitDefaultValue=false)]
        public bool? ContainsBirthDate { get; set; }

        /// <summary>
        /// True if the input contains passport numbers.
        /// </summary>
        /// <value>True if the input contains passport numbers.</value>
        [DataMember(Name="ContainsPassportNumber", EmitDefaultValue=false)]
        public bool? ContainsPassportNumber { get; set; }

        /// <summary>
        /// True if the input contains drivers license numbers.
        /// </summary>
        /// <value>True if the input contains drivers license numbers.</value>
        [DataMember(Name="ContainsDriversLicense", EmitDefaultValue=false)]
        public bool? ContainsDriversLicense { get; set; }

        /// <summary>
        /// True if the input contains social security numbers.
        /// </summary>
        /// <value>True if the input contains social security numbers.</value>
        [DataMember(Name="ContainsSocialSecurityNumber", EmitDefaultValue=false)]
        public bool? ContainsSocialSecurityNumber { get; set; }

        /// <summary>
        /// True if the input contains taxpayer IDs.
        /// </summary>
        /// <value>True if the input contains taxpayer IDs.</value>
        [DataMember(Name="ContainsTaxpayerID", EmitDefaultValue=false)]
        public bool? ContainsTaxpayerID { get; set; }

        /// <summary>
        /// True if the input contains credit card numbers.
        /// </summary>
        /// <value>True if the input contains credit card numbers.</value>
        [DataMember(Name="ContainsCreditCardNumber", EmitDefaultValue=false)]
        public bool? ContainsCreditCardNumber { get; set; }

        /// <summary>
        /// True if the input contains credit card expiration dates.
        /// </summary>
        /// <value>True if the input contains credit card expiration dates.</value>
        [DataMember(Name="ContainsCreditCardExpirationDate", EmitDefaultValue=false)]
        public bool? ContainsCreditCardExpirationDate { get; set; }

        /// <summary>
        /// True if the input contains credit card verification codes.
        /// </summary>
        /// <value>True if the input contains credit card verification codes.</value>
        [DataMember(Name="ContainsCreditCardVerificationCode", EmitDefaultValue=false)]
        public bool? ContainsCreditCardVerificationCode { get; set; }

        /// <summary>
        /// True if the input contains bank account numbers.
        /// </summary>
        /// <value>True if the input contains bank account numbers.</value>
        [DataMember(Name="ContainsBankAccountNumber", EmitDefaultValue=false)]
        public bool? ContainsBankAccountNumber { get; set; }

        /// <summary>
        /// True if the input contains IBANs.
        /// </summary>
        /// <value>True if the input contains IBANs.</value>
        [DataMember(Name="ContainsIBAN", EmitDefaultValue=false)]
        public bool? ContainsIBAN { get; set; }

        /// <summary>
        /// True if the input contains health insurance numbers.
        /// </summary>
        /// <value>True if the input contains health insurance numbers.</value>
        [DataMember(Name="ContainsHealthInsuranceNumber", EmitDefaultValue=false)]
        public bool? ContainsHealthInsuranceNumber { get; set; }

        /// <summary>
        /// True if the input contains bearer tokens.
        /// </summary>
        /// <value>True if the input contains bearer tokens.</value>
        [DataMember(Name="ContainsBearerToken", EmitDefaultValue=false)]
        public bool? ContainsBearerToken { get; set; }

        /// <summary>
        /// True if the input contains HTTP cookies.
        /// </summary>
        /// <value>True if the input contains HTTP cookies.</value>
        [DataMember(Name="ContainsHttpCookie", EmitDefaultValue=false)]
        public bool? ContainsHttpCookie { get; set; }

        /// <summary>
        /// True if the input contains private keys.
        /// </summary>
        /// <value>True if the input contains private keys.</value>
        [DataMember(Name="ContainsPrivateKeys", EmitDefaultValue=false)]
        public bool? ContainsPrivateKeys { get; set; }

        /// <summary>
        /// True if the input contains credentials (usernames/passwords).
        /// </summary>
        /// <value>True if the input contains credentials (usernames/passwords).</value>
        [DataMember(Name="ContainsCredentials", EmitDefaultValue=false)]
        public bool? ContainsCredentials { get; set; }

        /// <summary>
        /// True if the input contains deep web URLs (.onion).
        /// </summary>
        /// <value>True if the input contains deep web URLs (.onion).</value>
        [DataMember(Name="ContainsDeepWebUrls", EmitDefaultValue=false)]
        public bool? ContainsDeepWebUrls { get; set; }

        /// <summary>
        /// True if the input contains source code.
        /// </summary>
        /// <value>True if the input contains source code.</value>
        [DataMember(Name="ContainsSourceCode", EmitDefaultValue=false)]
        public bool? ContainsSourceCode { get; set; }

        /// <summary>
        /// True if the input contains IP addresses.
        /// </summary>
        /// <value>True if the input contains IP addresses.</value>
        [DataMember(Name="ContainsIpAddress", EmitDefaultValue=false)]
        public bool? ContainsIpAddress { get; set; }

        /// <summary>
        /// True if the input contains MAC addresses.
        /// </summary>
        /// <value>True if the input contains MAC addresses.</value>
        [DataMember(Name="ContainsMacAddress", EmitDefaultValue=false)]
        public bool? ContainsMacAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DlpDetectionResponse {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsEmailAddress: ").Append(ContainsEmailAddress).Append("\n");
            sb.Append("  ContainsPhoneNumber: ").Append(ContainsPhoneNumber).Append("\n");
            sb.Append("  ContainsStreetAddress: ").Append(ContainsStreetAddress).Append("\n");
            sb.Append("  ContainsPersonName: ").Append(ContainsPersonName).Append("\n");
            sb.Append("  ContainsBirthDate: ").Append(ContainsBirthDate).Append("\n");
            sb.Append("  ContainsPassportNumber: ").Append(ContainsPassportNumber).Append("\n");
            sb.Append("  ContainsDriversLicense: ").Append(ContainsDriversLicense).Append("\n");
            sb.Append("  ContainsSocialSecurityNumber: ").Append(ContainsSocialSecurityNumber).Append("\n");
            sb.Append("  ContainsTaxpayerID: ").Append(ContainsTaxpayerID).Append("\n");
            sb.Append("  ContainsCreditCardNumber: ").Append(ContainsCreditCardNumber).Append("\n");
            sb.Append("  ContainsCreditCardExpirationDate: ").Append(ContainsCreditCardExpirationDate).Append("\n");
            sb.Append("  ContainsCreditCardVerificationCode: ").Append(ContainsCreditCardVerificationCode).Append("\n");
            sb.Append("  ContainsBankAccountNumber: ").Append(ContainsBankAccountNumber).Append("\n");
            sb.Append("  ContainsIBAN: ").Append(ContainsIBAN).Append("\n");
            sb.Append("  ContainsHealthInsuranceNumber: ").Append(ContainsHealthInsuranceNumber).Append("\n");
            sb.Append("  ContainsBearerToken: ").Append(ContainsBearerToken).Append("\n");
            sb.Append("  ContainsHttpCookie: ").Append(ContainsHttpCookie).Append("\n");
            sb.Append("  ContainsPrivateKeys: ").Append(ContainsPrivateKeys).Append("\n");
            sb.Append("  ContainsCredentials: ").Append(ContainsCredentials).Append("\n");
            sb.Append("  ContainsDeepWebUrls: ").Append(ContainsDeepWebUrls).Append("\n");
            sb.Append("  ContainsSourceCode: ").Append(ContainsSourceCode).Append("\n");
            sb.Append("  ContainsIpAddress: ").Append(ContainsIpAddress).Append("\n");
            sb.Append("  ContainsMacAddress: ").Append(ContainsMacAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DlpDetectionResponse);
        }

        /// <summary>
        /// Returns true if DlpDetectionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of DlpDetectionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DlpDetectionResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CleanResult == input.CleanResult ||
                    (this.CleanResult != null &&
                    this.CleanResult.Equals(input.CleanResult))
                ) && 
                (
                    this.ContainsEmailAddress == input.ContainsEmailAddress ||
                    (this.ContainsEmailAddress != null &&
                    this.ContainsEmailAddress.Equals(input.ContainsEmailAddress))
                ) && 
                (
                    this.ContainsPhoneNumber == input.ContainsPhoneNumber ||
                    (this.ContainsPhoneNumber != null &&
                    this.ContainsPhoneNumber.Equals(input.ContainsPhoneNumber))
                ) && 
                (
                    this.ContainsStreetAddress == input.ContainsStreetAddress ||
                    (this.ContainsStreetAddress != null &&
                    this.ContainsStreetAddress.Equals(input.ContainsStreetAddress))
                ) && 
                (
                    this.ContainsPersonName == input.ContainsPersonName ||
                    (this.ContainsPersonName != null &&
                    this.ContainsPersonName.Equals(input.ContainsPersonName))
                ) && 
                (
                    this.ContainsBirthDate == input.ContainsBirthDate ||
                    (this.ContainsBirthDate != null &&
                    this.ContainsBirthDate.Equals(input.ContainsBirthDate))
                ) && 
                (
                    this.ContainsPassportNumber == input.ContainsPassportNumber ||
                    (this.ContainsPassportNumber != null &&
                    this.ContainsPassportNumber.Equals(input.ContainsPassportNumber))
                ) && 
                (
                    this.ContainsDriversLicense == input.ContainsDriversLicense ||
                    (this.ContainsDriversLicense != null &&
                    this.ContainsDriversLicense.Equals(input.ContainsDriversLicense))
                ) && 
                (
                    this.ContainsSocialSecurityNumber == input.ContainsSocialSecurityNumber ||
                    (this.ContainsSocialSecurityNumber != null &&
                    this.ContainsSocialSecurityNumber.Equals(input.ContainsSocialSecurityNumber))
                ) && 
                (
                    this.ContainsTaxpayerID == input.ContainsTaxpayerID ||
                    (this.ContainsTaxpayerID != null &&
                    this.ContainsTaxpayerID.Equals(input.ContainsTaxpayerID))
                ) && 
                (
                    this.ContainsCreditCardNumber == input.ContainsCreditCardNumber ||
                    (this.ContainsCreditCardNumber != null &&
                    this.ContainsCreditCardNumber.Equals(input.ContainsCreditCardNumber))
                ) && 
                (
                    this.ContainsCreditCardExpirationDate == input.ContainsCreditCardExpirationDate ||
                    (this.ContainsCreditCardExpirationDate != null &&
                    this.ContainsCreditCardExpirationDate.Equals(input.ContainsCreditCardExpirationDate))
                ) && 
                (
                    this.ContainsCreditCardVerificationCode == input.ContainsCreditCardVerificationCode ||
                    (this.ContainsCreditCardVerificationCode != null &&
                    this.ContainsCreditCardVerificationCode.Equals(input.ContainsCreditCardVerificationCode))
                ) && 
                (
                    this.ContainsBankAccountNumber == input.ContainsBankAccountNumber ||
                    (this.ContainsBankAccountNumber != null &&
                    this.ContainsBankAccountNumber.Equals(input.ContainsBankAccountNumber))
                ) && 
                (
                    this.ContainsIBAN == input.ContainsIBAN ||
                    (this.ContainsIBAN != null &&
                    this.ContainsIBAN.Equals(input.ContainsIBAN))
                ) && 
                (
                    this.ContainsHealthInsuranceNumber == input.ContainsHealthInsuranceNumber ||
                    (this.ContainsHealthInsuranceNumber != null &&
                    this.ContainsHealthInsuranceNumber.Equals(input.ContainsHealthInsuranceNumber))
                ) && 
                (
                    this.ContainsBearerToken == input.ContainsBearerToken ||
                    (this.ContainsBearerToken != null &&
                    this.ContainsBearerToken.Equals(input.ContainsBearerToken))
                ) && 
                (
                    this.ContainsHttpCookie == input.ContainsHttpCookie ||
                    (this.ContainsHttpCookie != null &&
                    this.ContainsHttpCookie.Equals(input.ContainsHttpCookie))
                ) && 
                (
                    this.ContainsPrivateKeys == input.ContainsPrivateKeys ||
                    (this.ContainsPrivateKeys != null &&
                    this.ContainsPrivateKeys.Equals(input.ContainsPrivateKeys))
                ) && 
                (
                    this.ContainsCredentials == input.ContainsCredentials ||
                    (this.ContainsCredentials != null &&
                    this.ContainsCredentials.Equals(input.ContainsCredentials))
                ) && 
                (
                    this.ContainsDeepWebUrls == input.ContainsDeepWebUrls ||
                    (this.ContainsDeepWebUrls != null &&
                    this.ContainsDeepWebUrls.Equals(input.ContainsDeepWebUrls))
                ) && 
                (
                    this.ContainsSourceCode == input.ContainsSourceCode ||
                    (this.ContainsSourceCode != null &&
                    this.ContainsSourceCode.Equals(input.ContainsSourceCode))
                ) && 
                (
                    this.ContainsIpAddress == input.ContainsIpAddress ||
                    (this.ContainsIpAddress != null &&
                    this.ContainsIpAddress.Equals(input.ContainsIpAddress))
                ) && 
                (
                    this.ContainsMacAddress == input.ContainsMacAddress ||
                    (this.ContainsMacAddress != null &&
                    this.ContainsMacAddress.Equals(input.ContainsMacAddress))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CleanResult != null)
                    hashCode = hashCode * 59 + this.CleanResult.GetHashCode();
                if (this.ContainsEmailAddress != null)
                    hashCode = hashCode * 59 + this.ContainsEmailAddress.GetHashCode();
                if (this.ContainsPhoneNumber != null)
                    hashCode = hashCode * 59 + this.ContainsPhoneNumber.GetHashCode();
                if (this.ContainsStreetAddress != null)
                    hashCode = hashCode * 59 + this.ContainsStreetAddress.GetHashCode();
                if (this.ContainsPersonName != null)
                    hashCode = hashCode * 59 + this.ContainsPersonName.GetHashCode();
                if (this.ContainsBirthDate != null)
                    hashCode = hashCode * 59 + this.ContainsBirthDate.GetHashCode();
                if (this.ContainsPassportNumber != null)
                    hashCode = hashCode * 59 + this.ContainsPassportNumber.GetHashCode();
                if (this.ContainsDriversLicense != null)
                    hashCode = hashCode * 59 + this.ContainsDriversLicense.GetHashCode();
                if (this.ContainsSocialSecurityNumber != null)
                    hashCode = hashCode * 59 + this.ContainsSocialSecurityNumber.GetHashCode();
                if (this.ContainsTaxpayerID != null)
                    hashCode = hashCode * 59 + this.ContainsTaxpayerID.GetHashCode();
                if (this.ContainsCreditCardNumber != null)
                    hashCode = hashCode * 59 + this.ContainsCreditCardNumber.GetHashCode();
                if (this.ContainsCreditCardExpirationDate != null)
                    hashCode = hashCode * 59 + this.ContainsCreditCardExpirationDate.GetHashCode();
                if (this.ContainsCreditCardVerificationCode != null)
                    hashCode = hashCode * 59 + this.ContainsCreditCardVerificationCode.GetHashCode();
                if (this.ContainsBankAccountNumber != null)
                    hashCode = hashCode * 59 + this.ContainsBankAccountNumber.GetHashCode();
                if (this.ContainsIBAN != null)
                    hashCode = hashCode * 59 + this.ContainsIBAN.GetHashCode();
                if (this.ContainsHealthInsuranceNumber != null)
                    hashCode = hashCode * 59 + this.ContainsHealthInsuranceNumber.GetHashCode();
                if (this.ContainsBearerToken != null)
                    hashCode = hashCode * 59 + this.ContainsBearerToken.GetHashCode();
                if (this.ContainsHttpCookie != null)
                    hashCode = hashCode * 59 + this.ContainsHttpCookie.GetHashCode();
                if (this.ContainsPrivateKeys != null)
                    hashCode = hashCode * 59 + this.ContainsPrivateKeys.GetHashCode();
                if (this.ContainsCredentials != null)
                    hashCode = hashCode * 59 + this.ContainsCredentials.GetHashCode();
                if (this.ContainsDeepWebUrls != null)
                    hashCode = hashCode * 59 + this.ContainsDeepWebUrls.GetHashCode();
                if (this.ContainsSourceCode != null)
                    hashCode = hashCode * 59 + this.ContainsSourceCode.GetHashCode();
                if (this.ContainsIpAddress != null)
                    hashCode = hashCode * 59 + this.ContainsIpAddress.GetHashCode();
                if (this.ContainsMacAddress != null)
                    hashCode = hashCode * 59 + this.ContainsMacAddress.GetHashCode();
                return hashCode;
            }
        }
    }

}
