/* 
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DLP.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DLP.Model
{
    /// <summary>
    /// Represents a time range in the audio that was redacted.
    /// </summary>
    [DataContract]
    public partial class RedactedAudioSegment :  IEquatable<RedactedAudioSegment>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RedactedAudioSegment" /> class.
        /// </summary>
        /// <param name="startTimeMs">Start time of the redacted segment in the audio, in milliseconds..</param>
        /// <param name="endTimeMs">End time of the redacted segment in the audio, in milliseconds..</param>
        /// <param name="redactedText">The original text that was redacted in this segment..</param>
        public RedactedAudioSegment(long? startTimeMs = default(long?), long? endTimeMs = default(long?), string redactedText = default(string))
        {
            this.StartTimeMs = startTimeMs;
            this.EndTimeMs = endTimeMs;
            this.RedactedText = redactedText;
        }
        
        /// <summary>
        /// Start time of the redacted segment in the audio, in milliseconds.
        /// </summary>
        /// <value>Start time of the redacted segment in the audio, in milliseconds.</value>
        [DataMember(Name="StartTimeMs", EmitDefaultValue=false)]
        public long? StartTimeMs { get; set; }

        /// <summary>
        /// End time of the redacted segment in the audio, in milliseconds.
        /// </summary>
        /// <value>End time of the redacted segment in the audio, in milliseconds.</value>
        [DataMember(Name="EndTimeMs", EmitDefaultValue=false)]
        public long? EndTimeMs { get; set; }

        /// <summary>
        /// The original text that was redacted in this segment.
        /// </summary>
        /// <value>The original text that was redacted in this segment.</value>
        [DataMember(Name="RedactedText", EmitDefaultValue=false)]
        public string RedactedText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RedactedAudioSegment {\n");
            sb.Append("  StartTimeMs: ").Append(StartTimeMs).Append("\n");
            sb.Append("  EndTimeMs: ").Append(EndTimeMs).Append("\n");
            sb.Append("  RedactedText: ").Append(RedactedText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RedactedAudioSegment);
        }

        /// <summary>
        /// Returns true if RedactedAudioSegment instances are equal
        /// </summary>
        /// <param name="input">Instance of RedactedAudioSegment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RedactedAudioSegment input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StartTimeMs == input.StartTimeMs ||
                    (this.StartTimeMs != null &&
                    this.StartTimeMs.Equals(input.StartTimeMs))
                ) && 
                (
                    this.EndTimeMs == input.EndTimeMs ||
                    (this.EndTimeMs != null &&
                    this.EndTimeMs.Equals(input.EndTimeMs))
                ) && 
                (
                    this.RedactedText == input.RedactedText ||
                    (this.RedactedText != null &&
                    this.RedactedText.Equals(input.RedactedText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StartTimeMs != null)
                    hashCode = hashCode * 59 + this.StartTimeMs.GetHashCode();
                if (this.EndTimeMs != null)
                    hashCode = hashCode * 59 + this.EndTimeMs.GetHashCode();
                if (this.RedactedText != null)
                    hashCode = hashCode * 59 + this.RedactedText.GetHashCode();
                return hashCode;
            }
        }
    }

}
